###############################################################
# Script: 02_differential_methylation.R
# Purposes: 
# Part 1. Identify differentially methylated CpGs between experimental groups.
# Part 2: Annotation of DMPs to their respective genes and CpG island contexts.
# Part 3: Functional enrichment analysis of genes annotated to DMPs
# Part 4: DMP enrichment relative to RRBS-MsPL targets in the reference genome

# Inputs:
# 1. Working directory with methylation_coverage data generated by nf-core/methylseq.
# 2. Sample description Excel file.
# 3. Worksheet name specifying the group comparison and sex (e.g Female_BBzP)
# 4. RRBS-MsPL target file containing chromosome and genomic coordinates of MsPL target sites in the reference genome.

# Usage:
#   Rscript 02_differential_methylation.R \
#       <working_directory> \
#       <sample_sheet2.xlsx> \
#       <worksheet_name> \
#       <RRBS_MsPl.xlsx>  

## Output:
## Differential methylation tables, summary statistics, Figures...
## DMP annotation tables, summary, figures... for gene and CpG island contexts
## DMP-annotated gene functional enrichment tables and figure
## DMP enrichment relative to RRBS-MsPL target summary statistics, tables and figures...

######################################################
#https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf
#https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5747346/
######################################################
## Command-line arguments
args <- commandArgs(trailingOnly = TRUE)
direc <- args[1]        # Working directory
target <- args[2]       # Sample sheet (.xlsx)
target_sheet <- args[3] # Sheet name in the Excel file
mspl_ref <- args[4]     # RRBS MsPl genome CpG Feature annotation file 40_220

## Uncomment the lines below only for interactive testing in RStudio
# direc <- "C:/Users/..."
# target <- "C:/Users/.../sample_sheet2.xlsx"
# target_sheet <- "Female_BBzP" or "Male_BBzP"
# mspl_ref <- "C:/Users/.../RRBS_MsPl_genome_CpG_Feature_annt_40_220.xlsx"

################################################################################
## List of required CRAN packages
cran_packages <- c("edgeR","readxl","writexl","sva","ggplot2","tibble",
                   "openxlsx","limma","tidyr","pheatmap","scatterplot3d",
                   "matrixStats","dplyr"
)

# Install BiocManager if needed
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}

## List of required Bioconductor packages
bioc_packages <- c("annotatr","GenomicRanges","genomation","ChIPseeker",
  "org.Rn.eg.db","TxDb.Rnorvegicus.UCSC.rn6.refGene","clusterProfiler"
)

## Install missing CRAN packages
missing_cran <- cran_packages[!sapply(cran_packages, requireNamespace, quietly = TRUE)]
if (length(missing_cran) > 0) {
  install.packages(missing_cran)
}

## Install missing Bioconductor packages
missing_bioc <- bioc_packages[!sapply(bioc_packages, requireNamespace, quietly = TRUE)]
if (length(missing_bioc) > 0) {
  BiocManager::install(missing_bioc)
}

## Load libraries
library(edgeR)
library(readxl)
library(writexl)
library(sva)
library(ggplot2)
library(openxlsx)
library(limma)
library(tidyr)
library(pheatmap)
library(annotatr)
library(GenomicRanges)
library(genomation)
library(matrixStats)
library(clusterProfiler)
library(ChIPseeker)
library(tibble)
library(scatterplot3d)
library(TxDb.Rnorvegicus.UCSC.rn6.refGene)
library(org.Rn.eg.db)
# Display available key types
keytypes(org.Rn.eg.db)

#=================================================================#
##***** PART 1: Differential methylation ***********************###
#=================================================================#
sex_chem <- strsplit(target_sheet, "_")[[1]]
sex <- sex_chem[1]
chem <- sex_chem[2]

#################################################################
set.seed(1234567)
## set working directory to the cov. files location
setwd(direc)
## load the target files
targets <- read.xlsx(target, sheet = target_sheet, rowNames=F)
targets

## Read in the coverage files of all samples using readBismark2DGE, and create a DGEList object
## Use the chromosome number and positions for annotation.
files <- targets$File
yallx <- readBismark2DGE(files, sample.names=targets$sample)
dim(yallx)

head(yallx$genes) #store the genomic locus
head(yallx$counts) #store methylated and unmethylated counts
head(yallx$samples) #store lib. size (aggregate) for methylated and unmethylated
table(yallx$genes$Chr) #Summary of the number of sites per chromosome

## Set working directory to save the output files
if (dir.exists(paste0(target_sheet,"_results"))) {
  unlink(paste0(target_sheet,"_results"), recursive = TRUE)
}
dir.create(paste0(target_sheet,"_results"))
setwd(paste0(target_sheet,"_results"))

## Library-level QC before collapsing
library_size_pup <- data.frame(
  sample = targets$sample,
  litter = targets$litter,
  Group = targets$Group,
  Me = yallx$samples$lib.size[
    seq(1, ncol(yallx), by = 2)
  ],
  Un = yallx$samples$lib.size[
    seq(2, ncol(yallx), by = 2)
  ]
)

##=================================
library_size_pup$Total <- library_size_pup$Me + library_size_pup$Un
library_size_pup

## Stacked bar plot of library size
png(file = paste0(target_sheet, "_library_Me_Un.png"), width = 7000, 
    height = 4000, res = 800)
par(mgp = c(3.2, 1, 0))
barplot(
  t(as.matrix(library_size_pup[, c("Me", "Un")])),
  names.arg = library_size_pup$sample,
  las = 2,
  cex.names = 0.9,
  ylab = "Read counts",
  font.lab = 2,
  main = paste0(sex, " ", chem,": Methylated and unmethylated reads per sample"),
  col = c("#5e3c99", "#e66101"),
  legend.text = c("Methylated", "Unmethylated"),
  args.legend = list(
    x = "topright",
    bty = "n"
  ),
  border = NA
)
dev.off()

#############################################################
## Collapse all pups within litter
collapse_litter <- function(yall, targets) {
  counts <- yall$counts
  litters <- unique(targets$litter)
  counts_litter <- matrix(
    0,
    nrow = nrow(counts),
    ncol = 2 * length(litters),
    dimnames = list(
      rownames(counts),
      NULL
    )
  )
  colnames_litter <- character(2 * length(litters))
  j <- 1
  for (L in litters) {
    ## Identify all libraries belonging to this litter
    samples <- targets$sample[
      targets$litter == L
    ]
    ## Choose a representative litter-level sample name e.g. Ctrl_2
    sample_name <- samples[1]
    ## Identify methylated/unmethylated columns
    me_cols <- paste0(samples, "-Me")
    un_cols <- paste0(samples, "-Un")
    
    ## Sum pups belonging to the same litter
    counts_litter[, j] <-
      rowSums(
        counts[, me_cols, drop = FALSE]
      )
    counts_litter[, j + 1] <-
      rowSums(
        counts[, un_cols, drop = FALSE]
      )
    ## Litter-level display name
    colnames_litter[j] <-
      paste0(sample_name, "-Me")
    colnames_litter[j + 1] <-
      paste0(sample_name, "-Un")
    j <- j + 2
  }
  colnames(counts_litter) <- colnames_litter
  counts_litter
}

##==================================
counts_litter <- collapse_litter(
  yallx,
  targets
)
head(counts_litter)

## make a litter target table to be used for downstream analysis
if ("batch" %in% colnames(targets)) {
  targets_litter <- targets[
    !duplicated(targets$litter),
    c("litter", "sample", "Group", "batch")
  ]
} else{
  targets_litter <- targets[
    !duplicated(targets$litter),
    c("litter", "sample", "Group")
  ]
}
targets_litter
##===========================
rownames(targets_litter) <- targets_litter$litter
litter_to_sample <- targets_litter$sample
names(litter_to_sample) <- targets_litter$litter

##===========================
sample_names <- sub(
  "-(Me|Un)$",
  "",
  colnames(counts_litter)
)
sample_names
##===========================
sample_to_litter <- setNames(
  targets_litter$litter,
  targets_litter$sample
)
count_litters <- sample_to_litter[sample_names]

###############################################################
## Create litter-level DGEList
yall_litter <- DGEList(
  counts = counts_litter,
  genes = yallx$genes
)

## Check the litter-level DGEList
head(yall_litter$counts)
head(rownames(yall_litter$counts))
head(rownames(yall_litter$genes))
tail(rownames(yall_litter$counts))
tail(rownames(yall_litter$genes))
dim(yallx$counts)
dim(yall_litter$counts)
identical(rownames(yall_litter$counts),rownames(yall_litter$genes))
head(yall_litter$genes[, c("Chr", "Locus")])

##=======================================
## assign the methylation and metadata objects 
targets <- targets_litter
yall <- yall_litter

##############################################################
### For convenience, sort DGEList in genomic order of locus
ChrNames <- paste0("chr",c(1:20,"M","X","Y"))
ChrNames

##================================
yall$genes$Chr <- factor(yall$genes$Chr, levels=ChrNames)
o <- order(yall$genes$Chr, yall$genes$Locus)
yall <- yall[o,]

## annotate the CpG locus with the identity of the nearest gene, 
## *search for the gene transcription start site (TSS) closest to the CpGs
TSS <- nearestTSS(yall$genes$Chr, yall$genes$Locus, species="Rn")
yall$genes$EntrezID <- TSS$gene_id
yall$genes$Symbol <- TSS$symbol
yall$genes$Strand <- TSS$strand
yall$genes$Distance <- TSS$distance
yall$genes$Width <- TSS$width
head(yall$genes)
head(yall)

## Save the library size i.e #Met and #unmet. in a data frame as a CSV file
libr_size<- data.frame(yall$samples)
write.csv(libr_size, file = paste0(target_sheet, "libr_size.csv"), row.names = T)

## CpG loci with low coverage are removed before downstream analysis as they provide
Methylation <- gl(2,1,ncol(yall), labels=c("Me","Un"))
Me <- yall$counts[, Methylation=="Me"]
Un <- yall$counts[, Methylation=="Un"]
Coverage <- Me + Un
head(Coverage)

## Detect outlier samples 
## method 1: cor heat map 
pdf(file = paste0(target_sheet, "_cor_heatmp_b4_BC.pdf"), width = 12, height = 9)
cor_mat <- cor(Me)
pheatmap(cor_mat, cutree_cols = 2, fontsize = 12)
dev.off()

## method 2: hierarchical clustering
pdf(file = paste0(target_sheet, "_hclust_b4_BC.pdf"), width = 12, height = 9)
htree <- hclust(dist(t(Me)), method = "average")
plot(htree)
dev.off()

## Method 3: PCA
#https://stackoverflow.com/questions/15624656/label-points-in-geom-point
par(mar = c(5,5,4,4))
pca <- prcomp(t(Me))
pca.dat <- pca$x
pca.var <- pca$sdev^2
pca.var.percent <- round(pca.var/sum(pca.var)*100, digits = 2)
pca.dat <- as.data.frame(pca.dat)

##======================================
pca_bf <- ggplot(pca.dat, aes(PC1, PC2)) +
  geom_point() +
  geom_text(label = rownames(pca.dat),hjust=0.1, vjust=0.1) +
  labs(x = paste0('PC1: ', pca.var.percent[1], ' %'),
       y = paste0('PC2: ', pca.var.percent[2], ' %'))
## save in png
ggsave(paste0(target_sheet, "_PCA_b4_BC.png"), plot = pca_bf, dpi = 300)
## Save in PDF
pdf(file = paste0(target_sheet, "_PCA_b4_BC.pdf"), width = 12, height = 9)
pca_bf
dev.off()

## As a conservative rule of thumb, it's required that a CpG site has a total count 
## (both met. and unmet.) of at least 8 in every sample b/4 it is considered downstream analysis.
HasCoverage <- rowSums(Coverage >= 8) >= round(nrow(targets) * 0.8) #80% of samples
table(HasCoverage)

## Also filter out CpGs that are never met. or always met, as they provide no information about DM:
HasBoth <- rowSums(Me) > 0 & rowSums(Un) > 0
table(HasBoth)

## Combine the two filtering criteria
table(HasCoverage, HasBoth)

## The DGEList object is subsetted to retain only the non-filtered loci:
y <- yall[HasCoverage & HasBoth,, keep.lib.sizes=FALSE]

####################################################################
## Collate all CpG in ChrY and remove from female analysis
if (sex == "Female") {
  ## collate all ChrY
  df_filtered1 <- y$counts[grepl("^chrY", rownames(y)), ]
  df_filtered1 <- as.data.frame(df_filtered1)
  ## Remove columns starting with "Un"
  df_export1 <- df_filtered1 %>%
    dplyr::select(-ends_with("-Un"))
  ## Write to Excel
  write_xlsx(df_export1, paste0(target_sheet, "_ChrY.xlsx"))
  head(df_export1)
  
  ## Remove contaminated ChrY from DMP analysis for female
  keepmc <- !grepl("^chrY", rownames(y))
  y <- y[keepmc, ]
}

##* To ensure that the met and unmet. reads for the same sample are treated on
##* the same scale, set the library sizes to be equal for each pair of libraries. 
##* by setting the library sizes for each sample to be the average of the total 
##* read counts for the met. $ unmet libraries:
TotalLibSize <- 0.5 * y$samples$lib.size[Methylation=="Me"] + 0.5 * y$samples$lib.size[Methylation=="Un"]
y$samples$lib.size <- rep(TotalLibSize, each=2)
y$samples

## Data Exploration
## * Generating multi-dimensional scaling (MDS) plots on the met. level (M-value) of the CpG sites. 
## *The M-value is calculated by the log of the ratio of met. and unmet. C’s, 
## *which is equivalent to the difference between met. & unmet C’s on the log scale.
##* A prior count of 2 is added to avoid logarithms of zero.
Me <- y$counts[, Methylation=="Me"]
Un <- y$counts[, Methylation=="Un"]
M <- log2(Me + 2) - log2(Un + 2)
colnames(M) <- targets$Sample

################################################################################
## EDA using pheatmap
cor_mat2 <- cor(M)
logM <- pheatmap(cor_mat2, cutree_cols = 2)
ggsave(paste0(target_sheet, "_pheatmap_log_me_un_b4_BC.png"), plot = logM, width=7, height=5,dpi = 300)
pdf(file = paste0(target_sheet, "_pheatmap_log_me_un_b4_BC.pdf"), width = 12, height = 9)
logM
dev.off()

pdf(file = paste0(target_sheet, "_hclust_log_me_un_b4_BC.pdf"), width=12, height = 9)
htree2 <- hclust(dist(t(M)), method = "average")
plot(htree2)
dev.off()

## *Generate a multi-dimensional scaling (MDS) plot to explore the overall differences
## *between the met. levels of the different samples
plotMDS(M, main="M-values")

## customized  mds plot
pdf(paste0(target_sheet, "scatter_plot_b4_BC.pdf"), width = 12, height = 9)
## Define group labels
sample_names = targets$Sample
group_labels <- targets$Group
## Define a vector of colors for each group
group_colors <- c("#f1a340", "#998ec3")
names(group_colors) <- c("Ctrl", paste0(chem))
## Generate the MDS plot
mds <- plotMDS(M, col = group_colors[group_labels], pch = 16, main = paste0(sex,": ", chem, " vs Control"))
## Add text labels for each point using sample names
text(mds$x, mds$y, labels = sample_names, pos = 3, cex = 0.8)
## Add a legend to indicate group colors
## legend("top-right", legend = names(group_colors), col = group_colors, pch = 16)
dev.off()
gc()

################################################################
## SVA part
## Initiate the model matrix to be used to fit the data
if ("batch" %in% colnames(targets)) {
  mod <- model.matrix(~ batch + Group, data=targets)
  #Initiate the null model to be compared when fitting the data
  mod0 <- model.matrix(~ batch,  data=targets)
} else {
  mod <- model.matrix(~ Group, data=targets)
  #Initiate the null model to be compared when fitting the data
  mod0 <- model.matrix(~ 1,  data=targets)
}

## Keep only rows where the count is greater than 5 in at least half of the samples.
## Otherwise, svseq would give an error if count values are too low.
keep_Me <- rowSums(Me > 5) >= (ncol(Me) * 0.5)
Me_filtered <- Me[keep_Me, ]

## Estimate the number of surrogate variables using methylated counts only, i.e Me
## Note: Optimal: Estimate number of SVs using untransformed counts (less bias in estimation)
n.sv <- num.sv(Me_filtered, mod, method = "be", B=100,seed = 100000)
cat("Optimal number of surrogate variables: ", n.sv)

## Run SVA to estimate surrogate variables
svseq <- svaseq(as.matrix(Me_filtered), mod, mod0, n.sv = n.sv, B=100) #use with raw methylated counts only
## svseq <- sva(M, mod, mod0, n.sv = n.sv, B=100) # use with normalized/log trasformed data
## View surrogate variables
svseq$sv

## Add SVs to targets data
sv_columns <- paste0("SV", 1:n.sv)  #Create column names: SV1, SV2, ...
for (i in seq_len(n.sv)) {
  targets[[sv_columns[i]]] <- svseq$sv[, i]
}

## Before design, Set Ctrl as reference
targets$Group <- relevel(factor(targets$Group), ref = "Ctrl")

## Design matrix
## *To identify DM loci btw the diff. groups, edgeR fits linear models
## *under a specified design matrix and testing for corresponding coefficients
## *or contrasts. 

## Design matrix with ("~0+batch+") or without ("~batch+") intercept
if ("batch" %in% colnames(targets)) {
  formula <- as.formula(paste0("~batch+",paste0(sv_columns,collapse = "+"),"+Group"))
} else {
  formula <- as.formula(paste0("~",paste0(sv_columns,collapse = "+"),"+Group"))
}

##=======================================
designSL <- model.matrix(formula, data = targets)
designSL

## Expand designSL to the full design matrix modeling the sample and methylation effects
design <- modelMatrixMeth(designSL)
design
################################################################
## Differential methylation analysis at CpG loci
## *Estimate dispersion just the way it's done for RNA_seq analysis to estimate for the 
## *diff. between the biological replicates
y <- estimateDisp(y, design) #enables common + trended + tagwise dispersion
y$common.dispersion
y$prior.df

#Testing for diff. met. CpG loci/sites using glmQLFit/glmQLFTest or glmFit/glmLRT
fit <- glmFit(y, design)

## When the design matrix is without intercept (i.e 0), use contrast as follows:
## Perform the actual testing using likelihood ratio tests (LRT) in edgeR directly 
qlf <- glmLRT(fit, coef = paste0("Group",chem))

## Examine the top set of most sig. met.CpG sites
topTags(qlf)

## Save significant results
## Get top tags (results) and convert to a data frame
result <- topTags(qlf, n = Inf)$table
#write.csv(result, file = paste0(target_sheet, "_all.csv"), row.names = TRUE)
dev.off()
gc()

## Calculates delta beta before and after correction ###
#******************BETA VALUE********************************###
beta <- Me / (Me + Un)
head(beta)
dim(beta)

##================================
colnames(beta) <- gsub("-Me", "", colnames(beta))
head(beta)
beta4corr <- beta ### to beta used 

## Methods 1: EDA using pheatmap for uncorrected beta values #####
zero_var <- sapply(seq_len(ncol(beta)), function(i) {
  x <- beta[, i]
  v <- var(x, na.rm = TRUE)
  is.na(v) || v == 0
})
zero_var

##=========================================
beta_data_clean <- beta[, !zero_var, drop = FALSE]
cor_beta <- cor(beta_data_clean, use = "pairwise.complete.obs")
cor_beta_plot <- pheatmap(cor_beta, cutree_cols = 2)
ggsave(paste0(target_sheet, "_pheatmap_beta_b4_BC.png"), plot = cor_beta_plot,
       width=7, height=5,dpi = 300)
pdf(file = paste0(target_sheet, "_pheatmap_beta_b4_BC.pdf"), width = 12, height = 9)
cor_beta_plot
dev.off()

## Methods 2: EDA using PCA for uncorrected beta values #########
data_mat_clean <- beta_data_clean[ apply(beta_data_clean, 1, function(x) all(is.finite(x))), ]
data_mat_clean <- data_mat_clean[ apply(data_mat_clean, 1, sd) > 0, ]
pca_res <- prcomp(t(data_mat_clean),center = T, scale. = T)

## Extract PCA results
pca_data <- as.data.frame(pca_res$x) %>% rownames_to_column("sample") %>%
  left_join(targets, by = "sample")

## Calculate explained variance
var_explained <- round(100 * summary(pca_res)$importance[2, 1:2], 1)

#============================================
p_pca <- ggplot(pca_data, aes(x = PC1, y = PC2, color = Group, shape = Group)) +
  geom_point(size = 5, alpha = 0.9) +   # increased point size
  scale_color_manual(values = c("Ctrl" = "#f1a340",setNames("#998ec3", chem))) +
  theme_minimal(base_size = 16) +
  labs(
    title = "B-value: Pre-batch-correction PCA",
    x = paste0("PC1 (", var_explained[1], "%)"),
    y = paste0("PC2 (", var_explained[2], "%)")
  ) +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )
p_pca
ggsave(paste0(target_sheet,"_PCA_beta_b4_BC.png"), 
       p_pca,width= 8,height=7,dpi = 600)

## Method 3: EDA using 3D scatter plot for uncorrected beta values ##
pca.dat_bf <- as.data.frame(pca_res$x)
pca.var_bf <- pca_res$sdev^2
pca.var_bf.percent <- round(pca.var_bf / sum(pca.var_bf) * 100, 2)

## Prepare group info
group_labels <- targets$Group
sample_names <- rownames(pca.dat_bf)
group_colors <- c("Ctrl" = "#f1a340", setNames("#998ec3", chem))
shapes <- ifelse(targets$Group == "Ctrl", 16, 17)

##=========================================
png(paste0(target_sheet,"_PCA_3D_beta_b4_BC.png"), width = 10,height = 10, 
    units = "in", res=600)
## Increase axis and label sizes
par(cex.axis = 2.3, cex.lab = 1.9, cex.main = 2.5)  #adjust font sizes

## Generate 3D plot  
pca3D <- scatterplot3d(x=pca.dat_bf$PC1,y=pca.dat_bf$PC2,z=pca.dat_bf$PC3,
                       color = group_colors[group_labels],pch = shapes,
                       cex.symbols = 3.5,  #Increase point size here
                       angle = 60,
                       xlab = paste0("PC1: ", pca.var_bf.percent[1], "%"),
                       ylab = paste0("PC2: ", pca.var_bf.percent[2], "%"),
                       zlab = paste0("PC3: ", pca.var_bf.percent[3], "%")
)
legend("top", legend = names(group_colors), col = group_colors, 
       pch = c(16,17),        # choose type of point
       pt.cex = 3.5,          #increase symbol size
       cex = 1.8,             #increase text size
       horiz = TRUE
)
dev.off()

##****** calculate methylation changes in beta values******##
control_cols <- grep("^Ctrl", colnames(beta))
treated_cols <- grep(paste0("^",chem), colnames(beta))

## handle NA first
beta[is.nan(beta)] <- NA

## Compute group mean
beta_control <- rowMeans(beta[, control_cols], na.rm = TRUE)
beta_treated <- rowMeans(beta[, treated_cols], na.rm = TRUE)

##***Calculate average methylation changes (delta-beta)***##
delta_beta <- beta_treated - beta_control

## Convert all to dataframe
delta_table <- data.frame(
  CpG = rownames(beta),
  beta_control = beta_control,
  beta_treated = beta_treated,
  delta_beta = delta_beta
)
head(delta_table)

##*****Calculate median beta-value (methylation changes)*******###
library(matrixStats)
## Compute group median methylation changes
beta_control_med <- matrixStats::rowMedians(
  data.matrix(beta[, control_cols]),na.rm = TRUE)

beta_treated_med <- matrixStats::rowMedians(
  data.matrix(beta[, treated_cols]),na.rm = TRUE)

## Median methylation changes
delta_beta_med <- beta_treated_med - beta_control_med

### Convert all to dataframe
delta_table_med <- data.frame(
  CpG = rownames(beta),
  beta_control_med = beta_control_med,
  beta_treated_med = beta_treated_med,
  delta_beta_med = delta_beta_med
)
head(delta_table_med)
dim(delta_table_med)

##************Beta-values Batch correction*****************######
## Remove batch effect using limma::removeBatchEffect
library(limma)
sv_colsB <- grep("^SV", names(targets), value = TRUE)

## Initiate the model matrix to be used to fit the data
if ("batch" %in% colnames(targets)) {
  corrected_mat <- removeBatchEffect(
    beta4corr,
    batch = targets$batch,
    covariates = as.matrix(targets[, sv_colsB, drop = FALSE])
  )
} else {
  corrected_mat <- removeBatchEffect(
    beta4corr,
    covariates = as.matrix(targets[, sv_colsB, drop = FALSE])
  )
}

## Methods 1: EDA using pheatmap for corrected beta values #####
zero_var_cor <- sapply(seq_len(ncol(corrected_mat)), function(i) {
  x <- corrected_mat[, i]
  v <- var(x, na.rm = TRUE)
  is.na(v) || v == 0
})
zero_var_cor

###############################################
beta_cor_clean <- corrected_mat[, !zero_var_cor, drop = FALSE]
cor_beta_corr <- cor(beta_cor_clean, use = "pairwise.complete.obs")
cor_beta_corr_plot <- pheatmap(cor_beta_corr, cutree_cols = 2)
ggsave(paste0(target_sheet, "_pheatmap_beta_AFT_BC.png"), plot = cor_beta_corr_plot,
       width=7, height=5,dpi = 300)
pdf(file = paste0(target_sheet, "_pheatmap_beta_AFT_BC.pdf"), width = 12, height = 9)
cor_beta_corr_plot
dev.off()

#########################################
corrected_mat_clean <- beta_cor_clean[ apply(beta_cor_clean, 1, function(x) all(is.finite(x))), ]
corrected_mat_clean <- corrected_mat_clean[ apply(corrected_mat_clean, 1, sd) > 0, ]

## Methods 2: EDA using PCA for corrected beta values #####
pca_res_cor <- prcomp(t(corrected_mat_clean),center = T, scale. = T)
pca_data_cor <- as.data.frame(pca_res_cor$x) %>% rownames_to_column("sample") %>%
  left_join(targets, by = "sample")

var_explained_cor <- round(100 * summary(pca_res_cor)$importance[2, 1:2], 1)
pca_cor <- ggplot(pca_data_cor, aes(x = PC1, y = PC2, color = Group, shape = Group)) +
  geom_point(size = 5, alpha = 0.9) +
  scale_color_manual(values = c("Ctrl" = "#f1a340", setNames("#998ec3", chem))) +
  theme_minimal(base_size = 16) +
  labs(
    title = "B-value: SVA-corrected PCA",
    x = paste0("PC1 (", var_explained_cor[1], "%)"),
    y = paste0("PC2 (", var_explained_cor[2], "%)")
  ) +
  theme(legend.position = "bottom")
pca_cor
ggsave(paste0(target_sheet, "_PCA_beta_SVA.png"), pca_cor, width = 8, 
       height = 7, dpi = 600)

## Methods 3: EDA using scatter plot for corrected beta values #####
pca.dat <- as.data.frame(pca_res_cor$x)
pca.var <- pca_res_cor$sdev^2
pca.var.percent <- round(pca.var / sum(pca.var) * 100, 2)

## Prepare group info
group_labels <- targets$Group
sample_names <- rownames(pca.dat)
group_colors <- c("Ctrl" = "#f1a340", setNames("#998ec3", chem))
shapes <- ifelse(targets$Group == "Ctrl", 16, 17)

png(paste0(target_sheet, "_PCA_3D_beta.png"), width = 10,height = 10, 
    units = "in", res=600)
## Increase axis and label sizes
par(cex.axis = 2.2, cex.lab = 1.8, cex.main = 2.5)

## Generate 3D plot with larger dots
pca3D <- scatterplot3d(x=pca.dat$PC1,y=pca.dat$PC2,z=pca.dat$PC3,
                       color = group_colors[group_labels],pch = shapes,
                       cex.symbols = 3.5, 
                       angle = 60,
                       xlab = paste0("PC1: ", pca.var.percent[1], "%"),
                       ylab = paste0("PC2: ", pca.var.percent[2], "%"),
                       zlab = paste0("PC3: ", pca.var.percent[3], "%")
)
legend("top", legend = names(group_colors), col = group_colors, 
       pch = c(16,17),        
       pt.cex = 3.5,     
       cex = 1.8,
       horiz = TRUE
)
dev.off()

##**** calculate methylation changes in corrected_mat values **##
control_colsB <- grep("^Ctrl", colnames(corrected_mat))
treated_colsB <- grep(paste0("^",chem), colnames(corrected_mat))

## handle NA first
corrected_mat[is.nan(corrected_mat)] <- NA
## Compute group mean/average
beta_controlB <- rowMeans(corrected_mat[, control_colsB], na.rm = TRUE)
beta_treatedB <- rowMeans(corrected_mat[, treated_colsB], na.rm = TRUE)
delta_betaB <- beta_treatedB - beta_controlB

## Covert all to dataframe
delta_tableB <- data.frame(
  CpG = rownames(corrected_mat),
  CR_beta_control = beta_controlB,
  CR_beta_treated = beta_treatedB,
  CR_delta_beta = delta_betaB
)
head(delta_tableB)

################**************####################################
## Merge the calculated delta beta with the diff. meth. results
result$CpG <- rownames(result)
fit_merged <- merge(result, delta_table, by = "CpG", all.x = TRUE)
fit_merged$delta_beta_PCT <- fit_merged$delta_beta * 100

##======================================
fit_merged <- merge(fit_merged, delta_tableB, by = "CpG", all.x = TRUE)
fit_merged$CR_delta_beta_PCT <- fit_merged$CR_delta_beta * 100
rownames(fit_merged) <- fit_merged$CpG

###################################################################
## Volcano plot for the diff. meth. results using delta beta  #####
logFC_threshold <- 10
pval_threshold <- 0.05

## Add a column to indicate sig. CpG sites with specific labels
fit_merged$Sig_COR <- with(fit_merged, 
                           ifelse(FDR < pval_threshold & CR_delta_beta_PCT >= logFC_threshold, "Hypermethylated",
                                  ifelse(FDR < pval_threshold & CR_delta_beta_PCT <= -logFC_threshold, "Hypomethylated", "Not Significant")))

## Create the volcano plot with customization
vcano_CR <- ggplot(fit_merged, aes(x = CR_delta_beta_PCT, y = -log10(FDR), color = Significant)) +
  geom_point(alpha = 0.6, size = 2) +
  scale_color_manual(values = c("Hypermethylated" = "#1f78b4", "Hypomethylated" = "#ef8a62", "Not Significant" = "grey")) +
  geom_hline(yintercept = -log10(pval_threshold), linetype = "dashed", color = "black") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed", color = "black") +
  scale_x_continuous(limits = c(-100, 100)) +  # FIXED y-axis range
  theme_minimal() +
  xlab("Methylation difference (%)") +
  ylab("-Log10 Adjusted P-value") +
  ggtitle(paste0(sex, ": ", chem," vs Control")) +
  labs(color = NULL) +
  theme(legend.position = "top", legend.text = element_text(size = 12))
vcano_CR
ggsave(paste0(target_sheet, "_volcano_pct_sva.png"), plot = vcano_CR, width=7, height=5, dpi = 300)

###############################################################################
## Volcano plot for the diff. meth. results using LFC
logFC_threshold <- 1
pval_threshold <- 0.05

### Add a column to indicate sig. CpG sites with specific labels
fit_merged$Significant <- with(fit_merged,
                               ifelse(FDR < pval_threshold & logFC >= logFC_threshold, "Hypermethylated",
                                      ifelse(FDR < pval_threshold & logFC <= -logFC_threshold, "Hypomethylated", "Not Significant")))

## Create the volcano plot with customization
vcano_fc <- ggplot(fit_merged, aes(x = logFC, y = -log10(FDR), color = Significant)) +
  geom_point(alpha = 0.6, size = 2) +
  scale_color_manual(values = c("Hypermethylated" = "#1f78b4", "Hypomethylated" = "#ef8a62", "Not Significant" = "grey")) +
  geom_hline(yintercept = -log10(pval_threshold), linetype = "dashed", color = "black") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed", color = "black") +
  theme_minimal() +
  xlab("Log2 Fold Change") +
  ylab("-Log10 Adjusted P-value") +
  ggtitle(paste0(sex, ": ", chem," vs Control")) +
  labs(color = NULL) +
  theme(legend.position = "top", legend.text = element_text(size = 12))
ggsave(paste0(target_sheet, "_volcano_LFC.png"), plot = vcano_fc,width=7, height=5, dpi = 300)

##Save all results
write.csv(fit_merged, file = paste0(target_sheet, "_ALL.csv"), row.names = TRUE)

## Filter the results where FDR < 0.05 or PValue < 0.05
sig_result <- fit_merged[fit_merged$FDR < 0.05, ]
sig_resultP <- fit_merged[fit_merged$PValue < 0.05, ]
## Save the sig. results to a CSV file
#write.csv(sig_result, file = paste0(target_sheet, "_sig_all.csv"), row.names = TRUE)
write_xlsx(sig_result, paste0(target_sheet, "_sig_FDR.xlsx"))
write_xlsx(sig_resultP, paste0(target_sheet, "_sig_Pval.xlsx"))

#Add biological effect size filtering, e.g., abs. meth. diff. ≥10% (logFC ≈ 0.26)
sig_result2 <- fit_merged[fit_merged$FDR < 0.05 & abs(fit_merged$CR_delta_beta_PCT) >= 10, ]
write_xlsx(sig_result2, paste0(target_sheet, "_sig_FDR_pct10.xlsx"))

#Add biological effect size filtering, e.g., abs meth. diff. ≥5%
sig_result3 <- fit_merged[fit_merged$FDR < 0.05 & abs(fit_merged$CR_delta_beta_PCT) >= 5, ]
write_xlsx(sig_result3, paste0(target_sheet, "_sig_FDR_pct5.xlsx"))

#Examine the total number of DM sites in each direction at an FDR (BH) of 5%
summary(decideTests(qlf))
plotMD(qlf)

## Assess the correlation between LFC and delta beta.
fit_merged$FDR_sig <- fit_merged$FDR < 0.05
## Compute Pearson correlation
cor_res <- cor.test(fit_merged$logFC,fit_merged$CR_delta_beta,method = "spearman",
                    exact = FALSE)

## Extract estimate and P-values 
rho <- round(cor_res$estimate, 3)
#p_val <- signif(cor_res$p.value, 3)

## Make correlation plot to compare LFC with delta beta SVA-corrected
cor_lfcB <- ggplot(fit_merged, aes(x = logFC, y = CR_delta_beta, color = FDR_sig)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  annotate("text", x = Inf, y = Inf, label = paste0("Spearman \u03C1 = ", rho),
           hjust = 1.1, vjust = 1.5, size = 5) +
  scale_color_manual(
    values = c("FALSE" = "#bdbdbd",
               "TRUE" = "#8856a7"),
    labels = c("FDR \u2265 0.05", "FDR < 0.05"),
    name = "Significance"
  ) +
  geom_hline(yintercept = c(-0.1, 0.1), linetype = "dashed", color = "#dfc27d") +
  geom_vline(xintercept = c(-2, 2), linetype = "dashed", color = "#abd9e9") +
  #theme_classic() +              #white background without grid lines
  theme_bw() +                    #white background with grid lines
  labs(title = "Correlation: LogFC and \u03B2", y = "Beta value", x = "LogFC")
#cor_lfcB
ggsave(paste0(target_sheet, "_COR_LFC-deltabeta_sva.png"), plot = cor_lfcB, width=8, height=6, dpi = 300)

## correlation plot to compare LFC with delta beta uncorrected
cor_resb <- cor.test(fit_merged$logFC,fit_merged$delta_beta, method = "spearman",
                     exact = FALSE)
## Extract estimate and P-values 
rhob <- round(cor_resb$estimate, 3)
p_valb <- signif(cor_resb$p.value, 3)
rhob

## Make correlation plot to compare LFC with delta beta uncorrected ##
cor_lfcB2 <- ggplot(fit_merged, aes(x = logFC, y = delta_beta, color = FDR_sig)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  annotate("text", x = Inf, y = Inf, label = paste0("Spearman \u03C1 = ", rhob),
           hjust = 1.1, vjust = 1.5, size = 5) +
  scale_color_manual(
    values = c("FALSE" = "#bdbdbd",
               "TRUE" = "#8856a7"),
    labels = c("FDR \u2265 0.05", "FDR < 0.05"),
    name = "Significance"
  ) +
  geom_hline(yintercept = c(-0.1, 0.1), linetype = "dashed", color = "#dfc27d") +
  geom_vline(xintercept = c(-2, 2), linetype = "dashed", color = "#abd9e9") +
  #theme_classic() + 
  theme_bw() +
  labs(title = "Correlation: LogFC and \u03B2", y = "Beta value", x = "LogFC")
ggsave(paste0(target_sheet, "_COR_LFC-B.png"), plot = cor_lfcB2, width=8, height=6, dpi = 300)
gc()

##******* EDA plot using pheatmap for uncorrected M values ****##
## Remove CpGs with non-finite or zero variance
row_var <- apply(M, 1, var, na.rm = TRUE)
M_clean <- M[is.finite(row_var) & row_var > 0, ,drop = FALSE]

## Remove CpGs containing NA/Inf
M_clean <- M_clean[apply(M_clean, 1, function(x) all(is.finite(x))), , drop = FALSE]

## Select the 5,000 most variable CpGs
row_var <- apply(M_clean, 1, var)
n_top <- min(5000, nrow(M_clean))
top_cpgs <- order(row_var, decreasing = TRUE)[seq_len(n_top)]
M_top <- M_clean[top_cpgs, , drop = FALSE]

###############################################
cor_M <- cor(M_clean, use = "pairwise.complete.obs")
#M_plot <- pheatmap(cor_M, cutree_cols = 2)

M_plot <- pheatmap(cor_M)
ggsave(paste0(target_sheet, "_pheatmap_mvalue_B4_BC.png"), plot = M_plot,
       width=7, height=5,dpi = 600)
pdf(file = paste0(target_sheet, "_pheatmap_mvalue_B4_BC.pdf"), width = 12, height = 9)
M_plot
dev.off()

##******EDA plot using PCA for uncorrected M values****###
# pca_res <- prcomp(t(data_mat_clean),center = T, scale. = F) ## All CpG
pca_res <- prcomp(t(M_top), center = TRUE, scale. = FALSE)  #top 5k CpG

## Extract PCA results
pca_data <- as.data.frame(pca_res$x) %>% rownames_to_column("sample") %>%
  left_join(targets, by = "sample")

## Calculate explained variance
var_explained <- round(100 * summary(pca_res)$importance[2, 1:2], 1)

## Plot PCA
p_pca <- ggplot(pca_data, aes(x = PC1, y = PC2, color = Group, shape = Group)) +
  geom_point(size = 10, alpha = 0.9) +   # increased point size
  scale_color_manual(values = c("Ctrl" = "#f1a340",setNames("#998ec3", chem))) +
  theme_minimal(base_size = 27) +
  labs(
    title = "M-value: Pre-batch-correction PCA",
    x = paste0("PC1 (", var_explained[1], "%)"),
    y = paste0("PC2 (", var_explained[2], "%)")
  ) +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.justification = "center",
    plot.title = element_text(hjust = 0.5),
    axis.line = element_line(color = "black", linewidth = 0.5),
    axis.ticks = element_line(color = "black", linewidth = 0.5),
    axis.text = element_text(color = "black"),
    axis.title = element_text(color = "black")
  )
p_pca
ggsave(paste0(target_sheet,"_PCA_mvalue_b4_BC.png"), p_pca, width = 10, 
       height = 10, dpi = 600)

##****EDA plot using 3D scatterplot for uncorrected M values****##
pca.dat_bf <- as.data.frame(pca_res$x)
pca.var_bf <- pca_res$sdev^2
pca.var_bf.percent <- round(pca.var_bf / sum(pca.var_bf) * 100, 2)

## Prepare group info
group_labels <- targets$Group
sample_names <- rownames(pca.dat_bf)
group_colors <- c("Ctrl" = "#f1a340", setNames("#998ec3", chem))
shapes <- ifelse(targets$Group == "Ctrl", 16, 17)

png(paste0(target_sheet,"_PCA_3D_mvalue_BCBB.png"), width = 11,height = 10, 
    units = "in", res=600)

## Increase axis and label sizes
par(cex.axis = 2.5, cex.lab = 2.5, cex.main = 3.0, 
    #mar = c(2,15,2,0),  #yaxis
    oma = c(1, 1, 1, 1)) #zaxis 

## Generate 3D plot with larger dots
pca3D <- scatterplot3d(x=pca.dat_bf$PC1,y=pca.dat_bf$PC2,z=pca.dat_bf$PC3,
                       color = group_colors[group_labels],pch = shapes,
                       cex.symbols = 4,  # <-- Increase point size here
                       angle = 60,
                       xlab = paste0("PC1: ", pca.var_bf.percent[1], "%"),
                       ylab = paste0("PC2: ", pca.var_bf.percent[2], "%"),
                       zlab = paste0("PC3: ", pca.var_bf.percent[3], "%")
)
legend("top", legend = names(group_colors), col = group_colors, 
       pch = c(16,17),        
       pt.cex = 4.0,     
       cex = 2.5, 
       horiz = TRUE
)
dev.off()

##*** EDA plots of M-values after batch correction***############
## Remove batch effects using SVA surrogate variables
library(limma)
## Batch correction using limma::removeBatchEffect
sv_colsB <- grep("^SV", names(targets), value = TRUE)

## Initiate the model matrix to be used to fit the data
if ("batch" %in% colnames(targets)) {
  corrected_counts <- removeBatchEffect(
    M,
    batch = targets$batch,
    covariates = as.matrix(targets[, sv_colsB, drop = FALSE])
  )
} else {
  corrected_counts <- removeBatchEffect(
    M,
    covariates = as.matrix(targets[, sv_colsB, drop = FALSE])
  )
}

## Remove CpGs with non-finite or zero variance
row_var_cor <- apply(corrected_counts, 1, var, na.rm = TRUE)
M_cort_clean <- corrected_counts[is.finite(row_var_cor) & row_var_cor > 0, ,drop = FALSE]
# Remove CpGs containing NA/Inf
M_cort_clean <- M_cort_clean[apply(M_cort_clean, 1, function(x) all(is.finite(x))), , drop = FALSE]
# Select the 5,000 most variable CpGs
row_var_cor <- apply(M_cort_clean, 1, var)
n_top_cor <- min(5000, nrow(M_cort_clean))
top_cpgs_cor <- order(row_var_cor, decreasing = TRUE)[seq_len(n_top_cor)]
M_cort_top <- M_cort_clean[top_cpgs_cor, , drop = FALSE]

##******EDA plot using pheatmap for corrected M values****###
cor_M_corr <- cor(M_cort_clean, use = "pairwise.complete.obs")
cor_M_corr_plot <- pheatmap(cor_M_corr)
ggsave(paste0(target_sheet, "_pheatmap_mvalue_AFT_BC.png"), plot = cor_M_corr_plot,
       width=7, height=5,dpi = 300)
pdf(file = paste0(target_sheet, "_pheatmap_mvalue_AFT_BC.pdf"), width = 12, height = 9)
cor_M_corr_plot
dev.off()

##******EDA plot using PCA for corrected M values****###
pca_res_cor <- prcomp(t(M_cort_top),center = T, scale. = F)
pca_data_cor <- as.data.frame(pca_res_cor$x) %>% rownames_to_column("sample") %>%
  left_join(targets, by = "sample")

var_explained_cor <- round(100 * summary(pca_res_cor)$importance[2, 1:2], 1)
pca_cor <- ggplot(pca_data_cor, aes(x = PC1, y = PC2, color = Group, shape = Group)) +
  geom_point(size = 10, alpha = 0.9) +
  scale_color_manual(values = c("Ctrl" = "#f1a340", setNames("#998ec3", chem))) +
  theme_minimal(base_size = 27) +
  labs(
    title = "M-value: SVA-corrected PCA",
    x = paste0("PC1 (", var_explained_cor[1], "%)"),
    y = paste0("PC2 (", var_explained_cor[2], "%)")
  ) +
  theme(#legend.position = "right",
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.justification = "center",
    axis.line = element_line(color = "black", linewidth = 0.5),
    axis.ticks = element_line(color = "black", linewidth = 0.5),
    axis.text = element_text(color = "black"),
    axis.title = element_text(color = "black"))
pca_cor
ggsave(paste0(target_sheet, "_PCA_mvalue_SVA.png"), pca_cor, width = 10, 
       height = 10, dpi = 600)

##******EDA plot using 3D scatterplot for corrected M values****###
pca.dat <- as.data.frame(pca_res_cor$x)
pca.var <- pca_res_cor$sdev^2
pca.var.percent <- round(pca.var / sum(pca.var) * 100, 2)

## Prepare group info
group_labels <- targets$Group
sample_names <- rownames(pca.dat)
group_colors <- c("Ctrl" = "#f1a340", setNames("#998ec3", chem))
shapes <- ifelse(targets$Group == "Ctrl", 16, 17)

png(paste0(target_sheet, "_PCA_3D_mvalue_AFT_BC.png"), width = 11,height = 10, 
    units = "in", res=600)
## Increase axis and label sizes
par(cex.axis = 2.5, cex.lab = 2.5, cex.main = 3.0, 
    #mar = c(2,15,2,0), ##yaxis
    oma = c(1, 1, 1, 1)) ## zaxis  # <- adjust font sizes

## Generate 3D plot with larger dots
pca3D <- scatterplot3d(x=pca.dat$PC1,y=pca.dat$PC2,z=pca.dat$PC3,
                       color = group_colors[group_labels],pch = shapes,
                       cex.symbols = 4.0,  # <-- Increase point size here
                       angle = 60,
                       xlab = paste0("PC1: ", pca.var.percent[1], "%"),
                       ylab = paste0("PC2: ", pca.var.percent[2], "%"),
                       zlab = paste0("PC3: ", pca.var.percent[3], "%")
)
legend("top", legend = names(group_colors), col = group_colors, 
       pch = c(16,17),        # type of point
       pt.cex = 4.0,      # increase symbol size
       cex = 2.5, # increase text size
       horiz = TRUE
)
dev.off()
gc()

#=================================================================#
##**** PART2: DMP Annotation ***********************************###
#=================================================================#
## Annotate CpG context using annotatr 
## Create GRanges object from the significant CpG loci
sig_result_gr <- GRanges(seqnames = sig_result$Chr,
                         ranges = IRanges(start = sig_result$Locus, end = sig_result$Locus),
                         strand = "*")

## Load relevant annotations for rat (Rn) — CpG and genic features
annotations <- c("rn6_cpg_islands", "rn6_cpg_shores", "rn6_cpg_shelves",
                 "rn6_genes_promoters", "rn6_genes_5UTRs", "rn6_genes_intergenic",
                 "rn6_genes_exons", "rn6_genes_introns", "rn6_genes_3UTRs")

## Build annotations and annotate
annots <- build_annotations(genome='rn6',annotations=annotations)
annots <- trim(annots) #if any, remove the out-of-bound part of the range but not remove the ranges entirely
annotated <- annotate_regions(regions=sig_result_gr, annotations=annots,ignore.strand=TRUE)

## Merge annotation with the diff. meth results
sig_result_annotated <- as.data.frame(annotated)
sig_result_annotated <- merge(sig_result, sig_result_annotated, 
                              by.x = c("Chr", "Locus"), by.y = c("seqnames", "start"))
## Save annotation results
#write.csv(sig_result_annotated, file = paste0(target_sheet, "_sig_island_context_annot.csv"),row.names = FALSE)
write_xlsx(sig_result_annotated, paste0(target_sheet, "_sig_island_context_annot.xlsx"))

####################################################################
## Annotate gene features using ChIPseeker (optional enhancement)
library(ChIPseeker)
library(TxDb.Rnorvegicus.UCSC.rn6.refGene)
#=======================
txdb <- TxDb.Rnorvegicus.UCSC.rn6.refGene
peak <- sig_result_gr
peakAnno <- annotatePeak(peak, TxDb = txdb, tssRegion = c(-3000, 3000), verbose = FALSE)

## Plot the distribution of gene feature annotations as a pie chart
pdf(paste0(target_sheet,"_genomic_feature_annot_piechart.pdf"))
plotAnnoPie(peakAnno)
dev.off()

## Save gene feature annotations results
peakAnno_df <- as.data.frame(peakAnno)
#write.csv(peakAnno_df, paste0(target_sheet, "_ChIPseeker_peak_annot.csv", row.names = FALSE))
write_xlsx(peakAnno_df,  paste0(target_sheet, "_ChIPseeker_peak_annot.xlsx"))

###############################################################################
## Annotate all regions, including intergenic
peakAnnoBB <- annotatePeak(sig_result_gr, 
                           TxDb = txdb, 
                           tssRegion = c(-3000, 3000), 
                           annoDb = "org.Rn.eg.db",  # Optional for gene symbols
                           verbose = FALSE)
## Extract annotated data
anno_dff2 <- as.data.frame(peakAnnoBB)
anno_dff2[c("width", "strand", "geneChr")] <- NULL #remove unwanted columns
write_xlsx(anno_dff2, paste0(target_sheet, "_sig_annot_intergenic.xlsx"))

## Annotate CpG island features 
library(genomation)
library(dplyr)
## Assign proper names BEFORE calling annotate_regions
sig_result_grB <- sig_result_gr
region_id <- paste0("region_", seq_along(sig_result_grB))
names(sig_result_grB) <- region_id  # very important!

## Define CpG annotations
annotationsB <- c("rn6_cpg_islands", "rn6_cpg_shores", "rn6_cpg_shelves")

## Build annotation set
annotsB <- build_annotations(genome = "rn6", annotations = annotationsB)
annotsB <- trim(annotsB) ## remove non-annotated positions that could cause error

## Annotate sig significant regions (GRanges object)
annotatedB <- annotate_regions(regions = sig_result_grB,annotations = annotsB,ignore.strand = TRUE)
cpg_anntB <- as.data.frame(annotatedB)
cpg_anntB[c("width", "strand","annot.tx_id","annot.strand","annot.gene_id","annot.symbol")] <- NULL #remove unwanted columns
write_xlsx(cpg_anntB, paste0(target_sheet, "_sig_island_context_annotated.xlsx"))

annotated_dfB <- data.frame(
  region_id = rownames(as.data.frame(annotatedB)),
  CpG_context = as.data.frame(annotatedB)$annot.type
)

## Add missing regions as "inter"
all_idsB <- names(sig_result_grB)
annotated_idsB <- unique(annotated_dfB$region_id)
others_idsB <- setdiff(all_idsB, annotated_idsB)

## Generate a dataframe containing the intergenic regions
others_dfB <- data.frame(region_id = others_idsB,CpG_context = "inter")

## Combine annotated and unannotated ("intergenic")
final_cpg_context <- rbind(annotated_dfB, others_dfB)

## Add region coordinates
region_coords <- as.data.frame(sig_result_grB)
region_coords$region_id <- names(sig_result_grB)
region_coords <- region_coords[, c("region_id", "seqnames", "start")]

## Merge inter with CpG context
cpg_merged <- left_join(region_coords, final_cpg_context, by = "region_id")
cpg_merged$CpG_context <- sub("^rn6_cpg_", "", cpg_merged$CpG_context) ### remove rn6_cpg_ from all values in columns "CpG_context"
cpg_merged$region_id <- NULL  ##drop column "region_id"
#write_xlsx(cpg_merged,  paste0(target_sheet, "_sig_CpG_context_others.xlsx"))

## Merge the island context annotation with sig. DMPs results (assuming it has Chr and Locus)
sig_result_annotated <- left_join(sig_result, cpg_merged,
                                  by = c("Chr" = "seqnames", "Locus" = "start"))
sig_result_annotated[c("EntrezID","Symbol","Strand","Distance","Width")] <- NULL 

## Optional: Save result
#write.csv(sig_result_annotated,  paste0(target_sheet, "_sig_annot_with_CpG_context_inter.csv", row.names = FALSE))
write_xlsx(sig_result_annotated, paste0(target_sheet, "_sig_annot_with_CpG_context_inter.xlsx"))

################################################################################
# Merge the CpG context data and the intergenic data with their nearest gene info
final_annotated <- merge(sig_result_annotated, anno_dff2, by.x = c("Chr", "Locus"), by.y = c("seqnames", "start"))
final_annotated[c("seqnames","start")] <- NULL #remove repeated/unwanted columns 
write_xlsx(final_annotated, paste0(target_sheet, "_sig_annotated_CpG_feature.xlsx"))

# Summarize counts and percentages of each annotation category
annotation_summary <- final_annotated %>%
  dplyr::count(CpG_context) %>%
  dplyr::mutate(percentage = n / sum(n) * 100)

## Plot the distribution of CpG island features annotated as a pie chart
pie_plot <- ggplot(annotation_summary, aes(x = "", y = percentage, fill = CpG_context)) +
  geom_col(width = 1, color = "white") +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(percentage, 1), "%")),
            position = position_stack(vjust = 0.5)) +
  labs(title = "Distribution of CpG Annotations",
       fill = "Annotation") +
  theme_void() +
  theme(legend.position = "right")
# Save pie chart as PDF
ggsave(paste0(target_sheet, "_island_context_annot_pie_chart.png"), 
       plot = pie_plot, width=7, height=5,dpi=300)

## Bar plot/histogram of CpG_context percentages
bar_plot <- ggplot(annotation_summary, aes(x = CpG_context, y = percentage, fill = CpG_context)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = paste0(round(percentage, 1), "%")), vjust = -0.3) +
  labs(title = "Percentage of CpG Annotations",
       x = "Annotation",
       y = "Percentage (%)") +
  theme_minimal() +
  theme(legend.position = "none")
# Save bar plot as PDF
ggsave(paste0(target_sheet, "_island_context_annot_bar_chart.png"),
       plot=bar_plot, dpi=300, width=5, height = 6)
gc()

#=================================================================#
##**PART 3: Functional Enrichment analysis using clusterProfiler*##
#=================================================================#
library(clusterProfiler)
library(org.Rn.eg.db)

## Use Entrez IDs from annotated results
entrez_ids <- unique(na.omit(final_annotated$geneId))
head(entrez_ids)

## Conduct GO: ALL (BB, MF, CC) enrichment
go_all_enrich <- enrichGO(gene = entrez_ids,
                          OrgDb = org.Rn.eg.db,
                          keyType = "ENTREZID",
                          ont = "ALL",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          readable = TRUE)

if (!is.null(go_all_enrich) && nrow(as.data.frame(go_all_enrich)) > 0) {
  # Filter GO:ALL enrichment results with adjusted p-value < 0.05
  sig_goall_results <- go_all_enrich@result[go_all_enrich@result$pvalue < 0.05, ]
  sig_goall_results <- as.data.frame(sig_goall_results)
  write_xlsx(sig_goall_results, paste0(target_sheet, "_GO_ALL_enrichment_sig.xlsx")) #significant GO
  
  #save the figure in .png format
  goall_plot <- dotplot(go_all_enrich, showCategory=15, font.size = 12) + ggtitle(paste0(sex, " ", chem,": Top enriched GO terms"))
  ggsave(paste0(target_sheet, "_oraGO_ALL_dotplot.png"), plot =  goall_plot, width = 7, height = 5, dpi = 300)
  
  #save the figure in .pdf format
  #pdf(paste0(target_sheet, "_GO_ALL_dotplot.pdf"))
  #dotplot(go_all_enrich, showCategory = 15)
  #dev.off()
} else {
  message("No enrichment results to plot.")
}

## Conduct GO: BP enrichment analysis
go_enrich <- enrichGO(gene = entrez_ids,
                      OrgDb = org.Rn.eg.db,
                      keyType = "ENTREZID",
                      ont = "BP",
                      pAdjustMethod = "BH",
                      pvalueCutoff = 0.05,
                      readable = TRUE)

if (!is.null(go_enrich) && nrow(as.data.frame(go_enrich)) > 0) {
  # Filter GO enrichment results with adjusted p-value < 0.05
  sig_go_results <- go_enrich@result[go_enrich@result$pvalue < 0.05, ]
  sig_go_results <- as.data.frame(sig_go_results)
  write_xlsx(sig_go_results, paste0(target_sheet, "_GO_BP_enrichment_sig.xlsx")) #significant GO
  
  #save the figure in .png format
  go_plot <- dotplot(go_enrich, showCategory=15, font.size = 12) + ggtitle(paste0(sex, " ", chem, ": Top enriched GO terms"))
  ggsave(paste0(target_sheet, "_oraGO_BP_dotplot.png"), plot =  go_plot, width = 7, height = 5, dpi = 600)
  
  #save the figure in .pdf format
  #pdf(paste0(target_sheet, "_GO_BP_dotplot.pdf"))
  #dotplot(go_enrich, showCategory = 15)
  #dev.off()
} else {
  message("No enrichment results to plot.")
}

##************ Conduct KEGG enrichment **********************##
kegg_enrich <- enrichKEGG(gene = entrez_ids,
                          organism = "rno",
                          pvalueCutoff = 0.05)

if (!is.null(kegg_enrich) && nrow(as.data.frame(kegg_enrich)) > 0) {
  # Filter GO enrichment results with adjusted p-value < 0.05
  sig_kegg_results <- kegg_enrich@result[kegg_enrich@result$pvalue < 0.05, ]
  sig_kegg_results <- as.data.frame(sig_kegg_results)
  write_xlsx(sig_kegg_results, paste0(target_sheet, "_KEGG_enrichment_sig.xlsx")) #significant GO
  
  #save the figure in .png format
  kegg_plot <- dotplot(kegg_enrich, showCategory=15, font.size = 12) + ggtitle(paste0(sex, " ", chem, ": Top enriched KEGG terms"))
  ggsave(paste0(target_sheet, "_KEGG_dotplot.png"), plot =  kegg_plot, width = 7, height = 5, dpi = 300)
  
  #save the figure in .pdf format
  #pdf(paste0(target_sheet, "_KEGG_barplot_.pdf"))
  #barplot(kegg_enrich, showCategory = 20)
  #dev.off()
} else {
  message("No enrichment results to plot.")
}
gc()

#======================================================================#
##**PART 4: CpG enrichment relative to the CpG RRBS reference********###
#======================================================================#
final_annotated$gene_feature <- sub(" \\(.*", "", final_annotated$annotation)
final_annotated$cpg_feature <- final_annotated$CpG_context
final_annotated$cpg_feature[final_annotated$cpg_feature == "others"] <- "inter"
head(final_annotated)

## Reference CpG annotation table (same columns)
## mspl_ref, it's an excel file containing pre-filtered RRBS targeted loci
ref_anno <- read.xlsx(mspl_ref)
ref_anno$gene_feature <- sub(" \\(.*", "", ref_anno$annotation)
ref_anno$cpg_feature <- ref_anno$annot.type
head(ref_anno)

## Function to calculate DMP enrichment relative to the RRBS target
enrich_test <- function(dmp_df, ref_df, feature_col) {
  dmp_counts <- dmp_df %>%
    dplyr::count(!!sym(feature_col), name = "dmp_count")
  ref_counts <- ref_df %>%
    dplyr::count(!!sym(feature_col), name = "ref_count")
  
  counts <- full_join(dmp_counts, ref_counts, by = feature_col) %>%
    replace(is.na(.), 0)
  
  total_dmp <- sum(counts$dmp_count)
  total_ref <- sum(counts$ref_count)
  
  results <- counts %>%
    rowwise() %>%
    mutate(
      fisher_p = fisher.test(
        matrix(c(
          dmp_count, total_dmp - dmp_count,
          ref_count, total_ref - ref_count
        ), nrow = 2)
      )$p.value,
      enrichment = (dmp_count / total_dmp) / (ref_count / total_ref),
      log2_enrichment = log2(enrichment)
    ) %>%
    ungroup() %>%
    mutate(fdr = p.adjust(fisher_p, method = "BH")) %>%
    arrange(desc(enrichment))
  
  return(results)
}

## Run DMP enrichment for the gene features (promoter, intron...)
gene_enrichment <- enrich_test(final_annotated, ref_anno, "gene_feature")
head(gene_enrichment)

## Run DMP enrichment for the CpG features (island, shore, shelf and inter)
cpg_enrichment <- enrich_test(final_annotated, ref_anno, "cpg_feature")
head(cpg_enrichment)

### Save results
write_xlsx(gene_enrichment, paste0(target_sheet, "_DMP_GeneFeature_Enrichment.xlsx"))
write_xlsx(cpg_enrichment, paste0(target_sheet, "_DMP_CpGFeature_Enrichment.xlsx"))

## Plot the gene feature enrichment
gene_plot <- ggplot(gene_enrichment, aes(x = reorder(gene_feature, log2_enrichment),
                                         y = log2_enrichment, fill = -log10(fdr))) +
  geom_bar(stat = "identity") +
  coord_flip() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_fill_gradient(low = "skyblue", high = "darkred") +
  labs(
    x = "Gene Feature",
    y = "log2(Enrichment ratio)",
    fill = "-log10(FDR)",
    title = paste0(sex, " ", chem, ": DMP Enrichment in Gene Features")
  ) +
  theme_bw(base_size = 12)
ggsave(paste0(target_sheet, "_DMP_gene_enrichment.png"), plot=gene_plot, dpi=600, width=6, height = 3)

## Plot the CpG island feature enrichment
cpg_plot <- ggplot(cpg_enrichment, aes(x = reorder(cpg_feature, log2_enrichment),
                                       y = log2_enrichment, fill = -log10(fdr))) +
  geom_bar(stat = "identity") +
  coord_flip() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_fill_gradient(low = "skyblue", high = "darkred") +
  labs(
    x = "CpG Feature",
    y = "log2(Enrichment ratio)",
    fill = "-log10(FDR)",
    title =  paste0(sex, " ", chem, ": DMP Enrichment in CpG Features")
  ) +
  theme_bw(base_size = 12)
ggsave(paste0(target_sheet, "_DMP_cpg_enrichment.png"), plot=cpg_plot, dpi=600, width=5.5, height = 2)
gc()
