###############################################################
# Script: 02_differential_methylation.R
# Purpose: Identify differentially methylated CpGs between experimental groups.
# Inputs:
# 1. Working directory with methylation_coverage data generated by nf-core/methylseq.
# 2. Sample description Excel file.
# 3. Worksheet name specifying the group comparison and sex (e.g Female_BBzP/Male_BBzP)
# Usage:
#   Rscript 02_differential_methylation.R \
#       <working_directory> \
#       <sample_sheet2.xlsx> \
#       <worksheet_name>
## Output:
#   Differential methylation tables, summary statistics, Figures...

###############################################################
#https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf
#https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5747346/
######################################################
## Command-line arguments
args <- commandArgs(trailingOnly = TRUE)
direc <- args[1]          # Working directory
target <- args[2]         # Sample sheet (.xlsx)
target_sheet <- args[3]   # Sheet name in the Excel file

## Uncomment the lines below only for interactive testing in RStudio
# direc <- "C:/Users/..."
# target <- "C:/Users/.../sample_sheet2.xlsx"
# target_sheet <- "Female_BBzP" or "Male_BBzP"

################################################################################
## List of required CRAN packages
cran_packages <- c("edgeR","readxl","writexl","sva","ggplot2",
                   "openxlsx","limma","tidyr","pheatmap",
                   "matrixStats"
)

# Install BiocManager if needed
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}

## List of required Bioconductor packages
bioc_packages <- c("annotatr","GenomicRanges","genomation",
  "org.Rn.eg.db"
)

## Install missing CRAN packages
missing_cran <- cran_packages[!sapply(cran_packages, requireNamespace, quietly = TRUE)]
if (length(missing_cran) > 0) {
  install.packages(missing_cran)
}

## Install missing Bioconductor packages
missing_bioc <- bioc_packages[!sapply(bioc_packages, requireNamespace, quietly = TRUE)]
if (length(missing_bioc) > 0) {
  BiocManager::install(missing_bioc)
}

# Load libraries
library(edgeR)
library(readxl)
library(writexl)
library(sva)
library(ggplot2)
library(openxlsx)
library(limma)
library(tidyr)
library(pheatmap)
library(annotatr)
library(GenomicRanges)
library(genomation)
library(matrixStats)
library(org.Rn.eg.db)
# Display available key types
keytypes(org.Rn.eg.db)

#################################################################
sex_chem <- strsplit(target_sheet, "_")[[1]]
sex <- sex_chem[1]
chem <- sex_chem[2]

#################################################################
set.seed(1234567)
#set working directory to the methylation_coverage files location
setwd(direc)

## load the target files
targets <- read.xlsx(target, sheet = target_sheet, rowNames=F)
targets

## Read in the coverage files of all samples using readBismark2DGE, and create DGEList object
files <- targets$File
yall <- readBismark2DGE(files, sample.names=targets$sample)
dim(yall)

head(yall$genes) #store the genomic locus
head(yall$counts) #store methylated and unmethylated counts

## yall$samples$group <- factor(targets$Group)
head(yall$samples) #store lib. size (aggregate) for methylated and unmethylated

## summary the number of sites per chromosome
table(yall$genes$Chr)

## For convenience sort DGEList in genomic order of locus
ChrNames <- paste0("chr",c(1:20,"M","X","Y"))
ChrNames

yall$genes$Chr <- factor(yall$genes$Chr, levels=ChrNames)
o <- order(yall$genes$Chr, yall$genes$Locus)
yall <- yall[o,]

##Set working directory to the output directory
if (dir.exists(paste0(target_sheet,"_results"))) {
  unlink(paste0(target_sheet,"_results"), recursive = TRUE)
}
dir.create(paste0(target_sheet,"_results"))
setwd(paste0(target_sheet,"_results"))

## annotate the CpG locus with the identity of the nearest gene, 
## **search for the gene transcription start site (TSS) closest to the CpGs
TSS <- nearestTSS(yall$genes$Chr, yall$genes$Locus, species="Rn")
yall$genes$EntrezID <- TSS$gene_id
yall$genes$Symbol <- TSS$symbol
yall$genes$Strand <- TSS$strand
yall$genes$Distance <- TSS$distance
yall$genes$Width <- TSS$width
head(yall$genes)
head(yall)

## Save the library size i.e #Met and #unmet. in data frame as a CSV file
libr_size<- data.frame(yall$samples)
#write.csv(libr_size, file = paste0(target_sheet, "libr_size.csv"), row.names = T)

## CpG loci with low coverage are removed prior to downstream analysis as they provide
Methylation <- gl(2,1,ncol(yall), labels=c("Me","Un"))
Me <- yall$counts[, Methylation=="Me"]
Un <- yall$counts[, Methylation=="Un"]
Coverage <- Me + Un
head(Coverage)

## Detect outlier samples 
## method 1: cor heat map 
pdf(file = paste0(target_sheet, "_cor_heatmp_b4_BC.pdf"), width = 12, height = 9)
cor_mat <- cor(Me)
pheatmap(cor_mat, cutree_cols = 2, fontsize = 12)
dev.off()

## method 2: hierarchical clustering
pdf(file = paste0(target_sheet, "_hclust_b4_BC.pdf"), width = 12, height = 9)
htree <- hclust(dist(t(Me)), method = "average")
plot(htree)
dev.off()

## method 3: PCA
#https://stackoverflow.com/questions/15624656/label-points-in-geom-point
par(mar = c(5,5,4,4))
pca <- prcomp(t(Me))
pca.dat <- pca$x
pca.var <- pca$sdev^2
pca.var.percent <- round(pca.var/sum(pca.var)*100, digits = 2)
pca.dat <- as.data.frame(pca.dat)

pca_bf <- ggplot(pca.dat, aes(PC1, PC2)) +
  geom_point() +
  geom_text(label = rownames(pca.dat),hjust=0.1, vjust=0.1) +
  labs(x = paste0('PC1: ', pca.var.percent[1], ' %'),
       y = paste0('PC2: ', pca.var.percent[2], ' %'))
##save in png
ggsave(paste0(target_sheet, "_PCA_b4_BC.png"), plot = pca_bf, dpi = 300)
##save in pdf
pdf(file = paste0(target_sheet, "_PCA_b4_BC.pdf"), width = 12, height = 9)
pca_bf
dev.off()

## As a conservative rule of thumb, it's required that a CpG site has a total count 
## (both met. and unmet.) of at least 8 in every sample b/4 it is considered downstream analysis.
HasCoverage <- rowSums(Coverage >= 8) >= round(nrow(targets) * 0.8) #80% of samples
table(HasCoverage)

## Also filter out CpGs that are never met. or always met. as they provide no information about DM:
HasBoth <- rowSums(Me) > 0 & rowSums(Un) > 0
table(HasBoth)

## combine the two filtering criteria
table(HasCoverage, HasBoth)

## The DGEList object is subsetted to retain only the non-filtered loci:
y <- yall[HasCoverage & HasBoth,, keep.lib.sizes=FALSE]

################################################################################
## Collate all CpG in ChrY and remove from female analysis
if (sex == "Female") {
  ## collate all ChrY
  df_filtered1 <- y$counts[grepl("^chrY", rownames(y)), ]
  df_filtered1 <- as.data.frame(df_filtered1)
  # Remove columns starting with "Un"
  df_export1 <- df_filtered1 %>%
    dplyr::select(-ends_with("-Un"))
  # Write to Excel
  write_xlsx(df_export1, paste0(target_sheet, "_ChrY.xlsx"))
  head(df_export1)
  
  ###Remove contaminated ChrY from DMP analysis for female
  keepmc <- !grepl("^chrY", rownames(y))
  y <- y[keepmc, ]
}

#*To ensure that the met. and unmet. reads for the same sample are treated on
#*the same scale, set the library sizes to be equal for each pair of libraries. 
#*by setting the library sizes for each sample to be the average of the total 
#*read counts for the met. $ unmet libraries:
TotalLibSize <- 0.5 * y$samples$lib.size[Methylation=="Me"] + 0.5 * y$samples$lib.size[Methylation=="Un"]
y$samples$lib.size <- rep(TotalLibSize, each=2)
y$samples

## Data Exploration
#* Generating multi-dimensional scaling (MDS) plots on the met. level (M-value) of the CpG sites. 
#*The M-value is calculated by the log of the ratio of met. and unmet. C’s, 
#*which is equivalent to the difference between met. & unmet C’s on the log-scale.
#*A prior count of 2 is added to avoid logarithms of zero.
Me <- y$counts[, Methylation=="Me"]
Un <- y$counts[, Methylation=="Un"]
M <- log2(Me + 2) - log2(Un + 2)
colnames(M) <- targets$Sample

################################################################################
## EDA using pheatmap
cor_mat2 <- cor(M)
logM <- pheatmap(cor_mat2, cutree_cols = 2)
ggsave(paste0(target_sheet, "_pheatmap_log_me_un_b4_BC.png"), plot = logM, width=7, height=5,dpi = 300)
pdf(file = paste0(target_sheet, "_pheatmap_log_me_un_b4_BC.pdf"), width = 12, height = 9)
logM
dev.off()

pdf(file = paste0(target_sheet, "_hclust_log_me_un_b4_BC.pdf"), width=12, height = 9)
htree2 <- hclust(dist(t(M)), method = "average")
plot(htree2)
dev.off()

#*Generate a multi-dimensional scaling (MDS) plot to explore the overall differences
#*between the met. levels of the different samples
plotMDS(M, main="M-values")

## customized  mds plot
pdf(paste0(target_sheet, "scatter_plot_b4_BC.pdf"), width = 12, height = 9)
## Define group labels
sample_names = targets$Sample
group_labels <- targets$Group
## Define a vector of colors for each group
group_colors <- c("#f1a340", "#998ec3")
names(group_colors) <- c("Ctrl", paste0(chem))
## Generate the MDS plot
mds <- plotMDS(M, col = group_colors[group_labels], pch = 16, main = paste0(sex,": ", chem, " vs Control"))
## Add text labels for each point using sample names
text(mds$x, mds$y, labels = sample_names, pos = 3, cex = 0.8)
## Add a legend to indicate group colors
## legend("top-right", legend = names(group_colors), col = group_colors, pch = 16)
dev.off()
gc()

################################################################
## SVA part
#Initiate the model matrix to be used to fit the data
if ("batch" %in% colnames(targets)) {
  mod <- model.matrix(~ batch + Group, data=targets)
  #Initiate the null model to be compared when fitting the data
  mod0 <- model.matrix(~ batch,  data=targets)
} else {
  mod <- model.matrix(~ Group, data=targets)
  #Initiate the null model to be compared when fitting the data
  mod0 <- model.matrix(~ 1,  data=targets)
}

## Keep only rows where the count is greater than 5 in at least half of the samples.
## otherwise, svseq would give an error is count values are too low.
keep_Me <- rowSums(Me > 5) >= (ncol(Me) * 0.5)
Me_filtered <- Me[keep_Me, ]

## Estimate the number of surrogate variables using methylated counts only i.e Me
## Note: Optimal; Estimate number of SVs using untransformed counts (less bias in estimation)
n.sv <- num.sv(Me_filtered, mod, method = "be", B=100,seed = 100000)
cat("Optimal number of surrogate variables: ", n.sv)

### Run SVA to estimate surrogate variables
svseq <- svaseq(as.matrix(Me_filtered), mod, mod0, n.sv = n.sv, B=100) #use with raw methylated counts only
#svseq <- sva(M, mod, mod0, n.sv = n.sv, B=100) # use with normalized/log trasformed data
# View surrogate variables
svseq$sv

## Add SVs to targets data
sv_columns <- paste0("SV", 1:n.sv)  #Create column names: SV1, SV2, ...
for (i in seq_len(n.sv)) {
  targets[[sv_columns[i]]] <- svseq$sv[, i]
}

## Before design, Set Ctrl as reference
targets$Group <- relevel(factor(targets$Group), ref = "Ctrl")

## Design matrix
#*To identify DM loci btw the diff. groups, edgeR fits linear models
#*under a specified design matrix and testing for corresponding coefficients
#*or contrasts. 

# Design matrix with ("~0+batch+") or without ("~batch+") intercept
if ("batch" %in% colnames(targets)) {
  formula <- as.formula(paste0("~batch+",paste0(sv_columns,collapse = "+"),"+Group"))
} else {
  formula <- as.formula(paste0("~",paste0(sv_columns,collapse = "+"),"+Group"))
}

designSL <- model.matrix(formula, data = targets)
designSL

## Expand designSL to the full design matrix modeling the sample and methylation effects
design <- modelMatrixMeth(designSL)
design
################################################################
## Differential methylation analysis at CpG loci
#*Estimate dispersion just the way it's done for RNA_seq analysis to estimate for the 
#*diff. between the biological replicates
y <- estimateDisp(y, design) #enables common + trended + tagwise dispersion
y$common.dispersion
y$prior.df

#Testing for diff. met. CpG loci/sites using glmQLFit/glmQLFTest or glmFit/glmLRT
fit <- glmFit(y, design)

##When the design matrix is without intercept (i.e 0) use contrast as follows:
#Perform the actual testing using likelihood ratio tests (LRT) in edgeR directly 
qlf <- glmLRT(fit, coef = paste0("Group",chem))

#Examine the top set of most sig. met.CpG sites
topTags(qlf)

##Save significant results
# Get top tags (results) and convert to a data frame
result <- topTags(qlf, n = Inf)$table
#write.csv(result, file = paste0(target_sheet, "_all.csv"), row.names = TRUE)
dev.off()
gc()

################################################################
#******************BETA VALUE********************************##
beta <- Me / (Me + Un)
head(beta)
dim(beta)

###############
colnames(beta) <- gsub("-Me", "", colnames(beta))
head(beta)
beta4corr <- beta

###############################################################
## calculate methylation changes in beta values
control_cols <- grep("^Ctrl", colnames(beta))
treated_cols <- grep(paste0("^",chem), colnames(beta))

## handle NA first
beta[is.nan(beta)] <- NA

## Compute group mean
beta_control <- rowMeans(beta[, control_cols], na.rm = TRUE)
beta_treated <- rowMeans(beta[, treated_cols], na.rm = TRUE)

## average methylation changes
delta_beta <- beta_treated - beta_control

## Covert all to dataframe
delta_table <- data.frame(
  CpG = rownames(beta),
  beta_control = beta_control,
  beta_treated = beta_treated,
  delta_beta = delta_beta
)
head(delta_table)

################################################################
##********** Calculate median beta-value********** #############
### calculate median methylation changes in beta values
library(matrixStats)
## Compute group median (med)
beta_control_med <- matrixStats::rowMedians(
  data.matrix(beta[, control_cols]),na.rm = TRUE)

beta_treated_med <- matrixStats::rowMedians(
  data.matrix(beta[, treated_cols]),na.rm = TRUE)

## Median methylation changes
delta_beta_med <- beta_treated_med - beta_control_med

### Covert all to dataframe
delta_table_med <- data.frame(
  CpG = rownames(beta),
  beta_control_med = beta_control_med,
  beta_treated_med = beta_treated_med,
  delta_beta_med = delta_beta_med
)
head(delta_table_med)
dim(delta_table_med)

###############################################################
library(limma)
## Batch correction using limma::removeBatchEffect
## Remove batch effect
sv_colsB <- grep("^SV", names(targets), value = TRUE)

#Initiate the model matrix to be used to fit the data
if ("batch" %in% colnames(targets)) {
  corrected_mat <- removeBatchEffect(
    beta4corr,
    batch = targets$batch,
    covariates = as.matrix(targets[, sv_colsB, drop = FALSE])
  )
} else {
  corrected_mat <- removeBatchEffect(
    beta4corr,
    covariates = as.matrix(targets[, sv_colsB, drop = FALSE])
  )
}

### calculate methylation changes in corrected_mat values
control_colsB <- grep("^Ctrl", colnames(corrected_mat))
treated_colsB <- grep(paste0("^",chem), colnames(corrected_mat))

## handle NA first
corrected_mat[is.nan(corrected_mat)] <- NA
## Compute group mean
beta_controlB <- rowMeans(corrected_mat[, control_colsB], na.rm = TRUE)
beta_treatedB <- rowMeans(corrected_mat[, treated_colsB], na.rm = TRUE)

## average methylation changes
delta_betaB <- beta_treatedB - beta_controlB
## Covert all to dataframe
delta_tableB <- data.frame(
  CpG = rownames(corrected_mat),
  CR_beta_control = beta_controlB,
  CR_beta_treated = beta_treatedB,
  CR_delta_beta = delta_betaB
)
head(delta_tableB)

###############################################################################
result$CpG <- rownames(result)
fit_merged <- merge(result, delta_table, by = "CpG", all.x = TRUE)
fit_merged$delta_beta_PCT <- fit_merged$delta_beta * 100
##############
fit_merged <- merge(fit_merged, delta_tableB, by = "CpG", all.x = TRUE)
fit_merged$CR_delta_beta_PCT <- fit_merged$CR_delta_beta * 100
rownames(fit_merged) <- fit_merged$CpG

###############################################################
## Volcano plot
logFC_threshold <- 10
pval_threshold <- 0.05

## Add a column to indicate significant loci with specific labels
fit_merged$Significant <- with(fit_merged, 
                               ifelse(FDR < pval_threshold & delta_beta_PCT >= logFC_threshold, "Hypermethylated",
                                      ifelse(FDR < pval_threshold & delta_beta_PCT <= -logFC_threshold, "Hypomethylated", "Not Significant")))
# Create the volcano plot with customizations
vcano <- ggplot(fit_merged, aes(x = delta_beta_PCT, y = -log10(FDR), color = Significant)) +
  geom_point(alpha = 0.6, size = 2) +
  scale_color_manual(values = c("Hypermethylated" = "#1f78b4", "Hypomethylated" = "#ef8a62", "Not Significant" = "grey")) +
  geom_hline(yintercept = -log10(pval_threshold), linetype = "dashed", color = "black") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed", color = "black") +
  scale_x_continuous(limits = c(-100, 100)) +  # FIXED y-axis range
  theme_minimal() +
  xlab("Methylation difference (%)") +
  ylab("-Log10 Adjusted P-value") +
  ggtitle(paste0(sex, ": ", chem," vs Control")) +
  labs(color = NULL) +
  theme(legend.position = "top", legend.text = element_text(size = 12))
vcano
ggsave(paste0(target_sheet, "_volcano_pct_b4_BC.png"), plot = vcano,width=7, height=5, dpi = 300)

#######
### Add a column to indicate significant genes with specific labels
fit_merged$Sig_COR <- with(fit_merged, 
                           ifelse(FDR < pval_threshold & CR_delta_beta_PCT >= logFC_threshold, "Hypermethylated",
                                  ifelse(FDR < pval_threshold & CR_delta_beta_PCT <= -logFC_threshold, "Hypomethylated", "Not Significant")))

# Create the volcano plot with customization
vcano_CR <- ggplot(fit_merged, aes(x = CR_delta_beta_PCT, y = -log10(FDR), color = Significant)) +
  geom_point(alpha = 0.6, size = 2) +
  scale_color_manual(values = c("Hypermethylated" = "#1f78b4", "Hypomethylated" = "#ef8a62", "Not Significant" = "grey")) +
  geom_hline(yintercept = -log10(pval_threshold), linetype = "dashed", color = "black") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed", color = "black") +
  scale_x_continuous(limits = c(-100, 100)) +  # FIXED y-axis range
  theme_minimal() +
  xlab("Methylation difference (%)") +
  ylab("-Log10 Adjusted P-value") +
  ggtitle(paste0(sex, ": ", chem," vs Control")) +
  labs(color = NULL) +
  theme(legend.position = "top", legend.text = element_text(size = 12))
vcano_CR
ggsave(paste0(target_sheet, "_volcano_pct_sva.png"), plot = vcano_CR, width=7, height=5, dpi = 300)

#################################################################
####### Volcano plot
logFC_threshold <- 1
pval_threshold <- 0.05

### Add a column to indicate significant loci with specific labels
fit_merged$Significant <- with(fit_merged,
                               ifelse(FDR < pval_threshold & logFC >= logFC_threshold, "Hypermethylated",
                                      ifelse(FDR < pval_threshold & logFC <= -logFC_threshold, "Hypomethylated", "Not Significant")))
# Create the volcano plot with customizations
vcano_fc <- ggplot(fit_merged, aes(x = logFC, y = -log10(FDR), color = Significant)) +
  geom_point(alpha = 0.6, size = 2) +
  scale_color_manual(values = c("Hypermethylated" = "#1f78b4", "Hypomethylated" = "#ef8a62", "Not Significant" = "grey")) +
  geom_hline(yintercept = -log10(pval_threshold), linetype = "dashed", color = "black") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed", color = "black") +
  theme_minimal() +
  xlab("Log2 Fold Change") +
  ylab("-Log10 Adjusted P-value") +
  ggtitle(paste0(sex, ": ", chem," vs Control")) +
  labs(color = NULL) +
  theme(legend.position = "top", legend.text = element_text(size = 12))
ggsave(paste0(target_sheet, "_volcano_LFC.png"), plot = vcano_fc,width=7, height=5, dpi = 300)

##Save all results
write.csv(fit_merged, file = paste0(target_sheet, "_ALL.csv"), row.names = TRUE)

###### Filter the results where FDR is less than 0.05
sig_result <- fit_merged[fit_merged$FDR < 0.05, ]
sig_resultP <- fit_merged[fit_merged$PValue < 0.05, ]
#write.csv(sig_result, file = paste0(target_sheet, "_sig_all.csv"), row.names = TRUE)
write_xlsx(sig_result, paste0(target_sheet, "_sig_FDR.xlsx"))
write_xlsx(sig_resultP, paste0(target_sheet, "_sig_Pval.xlsx"))

#Add biological effect size filtering, e.g., abs meth diff ≥10% (logFC ≈ 0.26)
sig_result2 <- fit_merged[fit_merged$FDR < 0.05 & abs(fit_merged$CR_delta_beta_PCT) >= 10, ]
write_xlsx(sig_result2, paste0(target_sheet, "_sig_FDR_pct10.xlsx"))

#Add biological effect size filtering, e.g., abs meth diff ≥5%
sig_result3 <- fit_merged[fit_merged$FDR < 0.05 & abs(fit_merged$CR_delta_beta_PCT) >= 5, ]
write_xlsx(sig_result3, paste0(target_sheet, "_sig_FDR_pct5.xlsx"))

#Examine the total number of DM sites in each direction at a FDR (BH) of 5%
summary(decideTests(qlf))
plotMD(qlf)

#########################
fit_merged$FDR_sig <- fit_merged$FDR < 0.05
# Compute Pearson correlation
#cor_res <- cor.test(fit_merged$logFC, fit_merged$CR_delta_beta, method = "pearson")
cor_res <- cor.test(fit_merged$logFC,fit_merged$CR_delta_beta,method = "spearman",
  exact = FALSE)

# Extract values
rho <- round(cor_res$estimate, 3)
rho
#p_val <- signif(cor_res$p.value, 3)

# Create plot
cor_lfcB <- ggplot(fit_merged, aes(x = logFC, y = CR_delta_beta, color = FDR_sig)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  annotate("text", x = Inf, y = Inf, label = paste0("Spearman \u03C1 = ", rho),
           hjust = 1.1, vjust = 1.5, size = 5) +
  scale_color_manual(
    values = c("FALSE" = "#bdbdbd",
               "TRUE" = "#8856a7"),
    labels = c("FDR \u2265 0.05", "FDR < 0.05"),
    name = "Significance"
  ) +
  geom_hline(yintercept = c(-0.1, 0.1), linetype = "dashed", color = "#dfc27d") +
  geom_vline(xintercept = c(-2, 2), linetype = "dashed", color = "#abd9e9") +
  #theme_classic() + #white background without grid lines
  theme_bw() +  #white background with grid lines
  labs(title = "Correlation: LogFC and \u03B2", y = "Beta value", x = "LogFC")
#cor_lfcB
ggsave(paste0(target_sheet, "_COR_LFC-B_sva.png"), plot = cor_lfcB, width=8, height=6, dpi = 300)

# Compute Pearson correlation
#cor_resb <- cor.test(fit_merged$logFC, fit_merged$delta_beta, method = "pearson")

cor_resb <- cor.test(fit_merged$logFC,fit_merged$delta_beta, method = "spearman",
                    exact = FALSE)
# Extract values
rhob <- round(cor_resb$estimate, 3)
rhob
#p_valb <- signif(cor_resb$p.value, 3)

# Create plot
cor_lfcB2 <- ggplot(fit_merged, aes(x = logFC, y = delta_beta, color = FDR_sig)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  annotate("text", x = Inf, y = Inf, label = paste0("Spearman \u03C1 = ", rhob),
           hjust = 1.1, vjust = 1.5, size = 5) +
  scale_color_manual(
    values = c("FALSE" = "#bdbdbd",
               "TRUE" = "#8856a7"),
    labels = c("FDR \u2265 0.05", "FDR < 0.05"),
    name = "Significance"
  ) +
  geom_hline(yintercept = c(-0.1, 0.1), linetype = "dashed", color = "#dfc27d") +
  geom_vline(xintercept = c(-2, 2), linetype = "dashed", color = "#abd9e9") +
  #theme_classic() + #white background without grid lines
  theme_bw() +  #white background with grid lines
  labs(title = "Correlation: LogFC and \u03B2", y = "Beta value", x = "LogFC")
ggsave(paste0(target_sheet, "_COR_LFC-B.png"), plot = cor_lfcB2, width=8, height=6, dpi = 300)
gc()
