###############################################################
# Script: 03_meth-pheno_ass.R
# Purposes: Methylation–Phenotype Association Analysis
# Part 1. Prepares methylation and phenotype data.
# Part 2: Evaluates associations using beta regression.
# Part 3: Performs linear-model-based association analysis.

# Inputs:
# 1. Working directory with methylation_coverage data generated by nf-core/methylseq.
# 2. Sample description Excel file.
# 3. Worksheet name specifying the phenotype of interest and sex (e.g Female_ACQ)

# Usage:
#   Rscript 03_meth-pheno_ass.R \
#       <working_directory> \
#       <sample_sheet2.xlsx> \
#       <worksheet_name> \

## Output:
##Beta regression association results (.csv/.xlsx)
##Limma association results (.csv/.xlsx)
##Generated plots and figures

## To ensure that R script accepts command-line arguments using commandArgs().
args <- commandArgs(trailingOnly = TRUE)
direc <- args[1] # 1st argument (working directory)
target <- args[2]
target_sheet <- args[3]

## Uncomment the lines below only for interactive testing in RStudio
# direc <- "C:/Users/..."
# target <- "C:/Users/.../sample_sheet2.xlsx"
# target_sheet <- "Female_REV" or "Male_ACQ"
##"Female_REV"/"Male_ACQ"/"Male_REV"
##** ACQ: Acquisition Learning; REV: Reversal Learning **##

#======================================================================#
##**PART 1: Data Processing *****************************************###
#======================================================================#
library(readxl); library(writexl); library(sva); library(ggplot2); library(openxlsx)
library(limma); library(tidyr); library(pheatmap); library(dplyr);library(tidyverse)
library(furrr); library(future); library(BiocParallel);library(DSS); library(bsseq)
library(stringr); library(future.apply);library("edgeR"); library("Matrix")
library("vroom"); library(matrixStats); library(ggrepel); library(Biobase);
library(variancePartition); library(betareg); library(doParallel);
library(foreach); library(corrplot)

###############################################################
sex_behav <- strsplit(target_sheet, "_")[[1]]
sex <- sex_behav[1]
behav <- sex_behav[2]

###############################################################
set.seed(1234567)
setwd(direc)

## load the target files
targets <- read.xlsx(target, sheet = target_sheet, rowNames=F)
targets

## Read in the coverage files of all samples using readBismark2DGE, and create DGEList object
files <- targets$File
yall <- readBismark2DGE(files, sample.names=targets$sample)
dim(yall)

head(yall$genes) #store the genomic locus
head(yall$counts) #store methylated and unmethylated counts

## yall$samples$group <- factor(targets$Group)
head(yall$samples) #store lib. size (aggregate) for methylated and unmethylated

## summary the number of sites per chromosome
table(yall$genes$Chr)

## For convenience sort DGEList in genomic order of locus
ChrNames <- paste0("chr",c(1:20,"M","X","Y"))
ChrNames
##=================
yall$genes$Chr <- factor(yall$genes$Chr, levels=ChrNames)
o <- order(yall$genes$Chr, yall$genes$Locus)
yall <- yall[o,]

## Set working directory to the output directory
if (dir.exists(paste0(target_sheet,"_results"))) {
  unlink(paste0(target_sheet,"_results"), recursive = TRUE)
}
dir.create(paste0(target_sheet,"_results"))
setwd(paste0(target_sheet,"_results"))

## Annotate the CpG locus with the identity of the nearest gene, 
## **search for the gene transcription start site (TSS) closest to the CpGs
TSS <- nearestTSS(yall$genes$Chr, yall$genes$Locus, species="Rn")
yall$genes$EntrezID <- TSS$gene_id
yall$genes$Symbol <- TSS$symbol
yall$genes$Strand <- TSS$strand
yall$genes$Distance <- TSS$distance
yall$genes$Width <- TSS$width
head(yall$genes)
head(yall)

## Save the library size i.e #Met and #unmet. in data frame as a CSV file
libr_size<- data.frame(yall$samples)
#write.csv(libr_size, file = paste0(target_sheet, "libr_size.csv"), row.names = T)

## CpG loci with low coverage are removed prior to downstream analysis as they provide
Methylation <- gl(2,1,ncol(yall), labels=c("Me","Un"))
Me <- yall$counts[, Methylation=="Me"]
Un <- yall$counts[, Methylation=="Un"]
Coverage <- Me + Un
head(Coverage)

##*As a conservative rule of thumb, it's required that a CpG site has a total count 
##(both met. and unmet.) of at least 8 in every sample b/4 it is considered downstream analysis.
#HasCoverage <- rowSums(Coverage >= 8) == nrow(targets) #each sample this is overly strict
HasCoverage <- rowSums(Coverage >= 5) >= round(nrow(targets) * 0.5) #80% of samples
table(HasCoverage)

###* Also filter out CpGs that are never met. or always met. as they provide no information about DM:
HasBoth <- rowSums(Me) > 0 & rowSums(Un) > 0
table(HasBoth)

###combine the two filtering criteria
table(HasCoverage, HasBoth)

### The DGEList object is subsetted to retain only the non-filtered loci:
y <- yall[HasCoverage & HasBoth,, keep.lib.sizes=FALSE]

################################################################################
## Collate all CpG in ChrY and remove from female analysis
if (sex == "Female") {
  ## collate all ChrY
  df_filtered1 <- y$counts[grepl("^chrY", rownames(y)), ]
  df_filtered1 <- as.data.frame(df_filtered1)
  # Remove columns starting with "Un"
  df_export1 <- df_filtered1 %>%
    dplyr::select(-ends_with("-Un"))
  # Write to Excel
  write_xlsx(df_export1, paste0(target_sheet, "_ChrY.xlsx"))
  head(df_export1)
  
  ###Remove contaminated ChrY from DMP analysis for female
  keepmc <- !grepl("^chrY", rownames(y))
  y <- y[keepmc, ]
}

#####################################################################
#*To ensure that the met. and unmet. reads for the same sample are treated on
#*the same scale, set the library sizes to be equal for each pair of libraries. 
TotalLibSize <- 0.5 * y$samples$lib.size[Methylation=="Me"] + 0.5 * y$samples$lib.size[Methylation=="Un"]
y$samples$lib.size <- rep(TotalLibSize, each=2)
y$samples

##Data Exploration
#* Generating multi-dimensional scaling (MDS) plots on the met. level (M-value) of the CpG sites. 
#*The M-value is calculated by the log of the ratio of met. and unmet. C’s, 
#*which is equivalent to the difference between met. & unmet C’s on the log-scale.
#*A prior count of 2 is added to avoid logarithms of zero.
Me <- y$counts[, Methylation=="Me"]
Un <- y$counts[, Methylation=="Un"]
#############################
M <- log2(Me + 2) - log2(Un + 2)
colnames(M) <- targets$Sample
#write.csv(M, file = paste0(target_sheet,"_Mvalue.csv"), row.names = TRUE)

################################################################################
library(edgeR); library(limma); library(sva)
###############################################################################
# Make matching sample names
sampleNames <- sub("-Me$", "", colnames(Me))  # "CtrlA1_1", "CtrlA1_2", ...
colnames(Me) <- sampleNames
colnames(Un) <- sampleNames

###########################
pseudocount <-0.5
meth_beta_squeezed <- (Me + pseudocount) / (Me + Un + 2*pseudocount)
head(meth_beta_squeezed)
dim(meth_beta_squeezed)

##################################
beta_value_long <- as.data.frame(meth_beta_squeezed) %>%
  pivot_longer(cols = everything(),
               names_to = "Variable",
               values_to = "Value")

# Plot density plots in multiple panels
densityB <- ggplot(beta_value_long, aes(x = Value)) +
  geom_density(fill = "skyblue", alpha = 0.8) +
  #facet_wrap(~ Variable, scales = "free") +
  facet_wrap(~ Variable, scales = "fixed") +
  theme_minimal() +
  xlab("Beta-value") + ylab("Frequency") +
  labs(title = "Methylation Proportions")
ggsave(paste0(target_sheet,"_beta_values_density.png"), plot = densityB, width = 17, height =10, dpi = 400)
densityB

################################################################################
# M-value transform
meth_mval <- log2(meth_beta_squeezed / (1 - meth_beta_squeezed))
##################
mvalue_long <- as.data.frame(meth_mval) %>%
  pivot_longer(cols = everything(),
               names_to = "Variable",
               values_to = "Value")

# Plot density plots in multiple panels
densityM <- ggplot(mvalue_long, aes(x = Value)) +
  geom_density(fill = "lightblue", alpha = 0.8) +
  #facet_wrap(~ Variable, scales = "free") +
  facet_wrap(~ Variable, scales = "fixed") +
  theme_minimal() +
  xlab("M-value") + ylab("Frequency") +
  labs(title = "Log2-transformed Methylation Proportions")
ggsave(paste0(target_sheet,"_mvalues_density.png"), plot = densityM, width = 17, height =10, dpi = 400)
densityM

##############################
png(paste0(target_sheet,"_boxplot.png"), width = 5000, height = 3000, res = 300)
boxplot(meth_mval, las = 2, outline = FALSE,
        main = "M-Value Distribution",
        ylab = "M-value",
        col = "cadetblue")
dev.off()

##############################
png(paste0(target_sheet,"_boxplot.png"), width = 5000, height = 3000, res = 300)
boxplot(meth_beta_squeezed, las = 2, outline = FALSE,
        main = "M-Value Distribution",
        ylab = "M-value",
        col = "deepskyblue")
dev.off()

############################
#ggplot(mvalue_long, aes(Variable, Value)) +
#  geom_boxplot()
############################
mat <- as.matrix(meth_mval)
keepmv <- rowVars(mat) > 0
M_filtered <- mat[keepmv, ]
dim(M_filtered)

############################
matB <- as.matrix(meth_beta_squeezed)
keepmv <- rowVars(matB) > 0
bv_filtered <- matB[keepmv, ]
dim(bv_filtered)

###############################################################################
# Model matrices
# Build supervised SVA (protect phenotype)
mod  <- model.matrix(~ Group + batch, data=targets)
mod0 <- model.matrix(~ batch, data=targets)

### Estimate the number of surrogate variables
#n.sv <- num.sv(M_filtered, mod, method = "be", B=100, seed = 1234567)
n.sv <- 2   #### For small sample size is small
cat("Optimal number of surrogate variables: ", n.sv)

## Run SVA to estimate surrogate variables
# Run SVA on filtered M-values
svobj <- sva(as.matrix(M_filtered), mod, mod0, n.sv = n.sv, B=100)

# Select top 1-2 SVs (n=15, avoid overfitting)
svdf <- as.data.frame(svobj$sv[, 1:min(2, ncol(svobj$sv)), drop=FALSE])
colnames(svdf) <- paste0("SV", seq_len(ncol(svdf)))
sv_names <- paste0("SV", 1:ncol(svdf))
sv_names

###############################################################
# Add SVs to phenotype data
sample_info <- targets[, c("sample", "batch", behav)]
pheno <- cbind(sample_info, svdf)
rownames(pheno) <- pheno$sample
pheno$sample <- NULL
pheno[[behav]] <- as.numeric(pheno[[behav]])

###############################################################
##================ BETAREG SECTION ==========================##
bv_filtered_df <- bv_filtered
rownames(bv_filtered_df) <- rownames(meth_beta_squeezed)
pheno <- pheno[colnames(bv_filtered_df), ]

################################################################
all(colnames(bv_filtered_df) == rownames(pheno), na.rm = TRUE)
stopifnot(all(colnames(bv_filtered_df) == rownames(pheno)))

#############################################################
## Check correlation btw SVA & phenotype; if highly correlated don't use SV
#library(corrplot)
# Correlation between each behaviour and each SV
beha_cor <- cor(as.numeric(pheno[[behav]]), svobj$sv, use = "pairwise.complete.obs")
beha_cor <- as.data.frame(beha_cor)
write_xlsx(beha_cor, paste0(target_sheet,"_SV_cor.xlsx"))

#############################################################
anova_beha <- apply(svobj$sv, 2, function(sv) {
  #a <- aov(sv ~ pheno[[behav]], data = pheno)
  a <- aov(as.formula(paste("sv ~", behav)), data = pheno)
  summary(a)[[1]][["Pr(>F)"]][1]
})

# named vector of p-values per SV
anova_beha <- as.data.frame(anova_beha)
write_xlsx(anova_beha, paste0(target_sheet,"_SV_cor_ANOVA.xlsx"))
anova_beha

#############################
# compute max absolute correlation btw outcomes/known & unknown batch/SV
max_abs_cor <- max(abs(beha_cor), na.rm = TRUE)
min_anova_p <- min(anova_beha, na.rm = TRUE)

use_batch <- TRUE
if(max_abs_cor >= 0.6 && min_anova_p < 0.05) {
  use_batch <- FALSE
}
message("max_abs_cor = ", round(max_abs_cor,3),
        "; min_SV_ANOVA_p = ", signif(min_anova_p,3),
        "; use_batch = ", use_batch)

#======================================================================#
##**PART 2: Association analysis with betareg ***********************###
#======================================================================#
#################################
if(use_batch) {
  formula_strA1 <- paste0("beta ~ ",behav," + batch + ", paste0(sv_names, collapse = " + "))
  formulaA1 <- as.formula(formula_strA1)
  formulaA1
} else {
  formula_strA1 <- paste0("beta ~ ",behav," + batch")
  formulaA1 <- as.formula(formula_strA1)
  formulaA1
}

################################################################################
process_row <- function(i, bv_filtered_df, pheno, formulaA1) {
  df <- data.frame(beta = as.numeric(bv_filtered_df[i, ]), pheno)
  if (length(unique(df$beta)) < 3) return(NULL)
  
  tryCatch({
    fit <- betareg(formulaA1, data = df)
    coefs <- summary(fit)$coefficients$mean
    if (!behav %in% rownames(coefs)) stop(paste(behav, "dropped"))
    out <- coefs[behav, ]
    data.frame(CpG = rownames(bv_filtered_df)[i],
               Estimate = out["Estimate"],
               StdErr   = out["Std. Error"],
               zval     = out["z value"],
               pval     = out["Pr(>|z|)"],
               Model    = "Full")
  })
}

library(future)
library(future.apply)

# Detect number of CPUs assigned by SLURM
slurm_cpus <- as.numeric(Sys.getenv("SLURM_CPUS_PER_TASK", "1"))

# If not defined, default to a safe number
if (is.na(slurm_cpus) || slurm_cpus < 2) slurm_cpus <- 20

############
options(
  future.availableCores.methods = c("system", "env"),
  mc.cores = slurm_cpus,
  future.globals.maxSize = 2 * 1024^3
)
plan(multisession, workers = slurm_cpus)

#### run the function
results_betareg_sv1 <- future_lapply(
  1:nrow(bv_filtered_df),
  function(i) process_row(i, bv_filtered_df, pheno, formulaA1)
)
results_betareg_sv1 <- do.call(rbind, results_betareg_sv1)

## Add FDR
results_betareg_sv1$adjusted_p_value <- p.adjust(results_betareg_sv1$pval, method = "BH")
rownames(results_betareg_sv1) <- results_betareg_sv1$CpG
results_betareg_sv1$CpG <- NULL
write.csv(results_betareg_sv1, file = paste0(target_sheet, "_Cor_all_betareg_sv.csv"))
##################
betareg_sig_SV1A <- results_betareg_sv1 %>% filter(adjusted_p_value < 0.05)
write.xlsx(betareg_sig_SV1A, paste0(target_sheet,"_SV_betareg_padj_sig.xlsx"),rowNames=T)
##################
betareg_sig_SV1P <- results_betareg_sv1 %>% filter(pval < 0.05)
write.xlsx(betareg_sig_SV1P, paste0(target_sheet,"_SV_betareg_pval_sig.xlsx"),rowNames=T)

#gc()
hist(results_betareg_sv1$pval, breaks = 500, col="pink")

#======================================================================#
##**PART 2: Association analysis with limma *************************###
#======================================================================#
# LIMMA Section uses M-Values
library(limma)
M_filtered_df <- M_filtered

if(use_batch) {
  formul<- as.formula(paste0("~ ", behav, " + batch + ", paste0(sv_names, collapse = "+")))
  formul
} else {
  formul<- as.formula(paste0("~ ", behav, " + batch"))
  formul
}

#===========================#
design <- model.matrix(formul, data = pheno)
limma_fit <- lmFit(M_filtered_df, design)

## empirical Bayes with robust=TRUE (more robust to outliers / variance heterogeneity)
limma_fit2 <- eBayes(limma_fit, robust = TRUE)

## diagnostic plot of residuals vs average expression
limma::plotSA(limma_fit2)    # shows mean-variance trend and effectiveness of shrinkage

## Top table
results_limma <- topTable(limma_fit2, coef = behav, number=Inf, sort.by="p")
write.csv(results_limma, file = paste0(target_sheet, "_Cor_all_limma_sv.csv"))
#write.xlsx(results_limma, paste0(target_sheet,"_SVN_limma.xlsx"),rowNames=T)

##===============
limma_sig_SV1 <- results_limma %>% filter( P.Value < 0.05)
dim(limma_sig_SV1)
write.xlsx(limma_sig_SV1, paste0(target_sheet,"_SV_limma_pval.xlsx"),rowNames=T)
limma_sig_SV2 <- results_limma %>% filter( adj.P.Val < 0.05)
dim(limma_sig_SV2)
write.xlsx(limma_sig_SV2, paste0(target_sheet,"_SV_limma_padj.xlsx"),rowNames=T)
hist(results_limma$P.Value, breaks = 500, col="pink4")

##########################################################
##***** Hybrid analysis *******************************###
betareg_padj <- results_betareg_sv1$adjusted_p_value
names(betareg_padj) <- rownames(results_betareg_sv1)

##================
betareg_pvals <- results_betareg_sv1$pval
names(betareg_pvals) <- rownames(results_betareg_sv1)

##================
limma_pvals <- results_limma$P.Value
names(limma_pvals) <- rownames(results_limma)

##================
## Align the CpG from both approaches
common_cpgs <- intersect(names(betareg_pvals), names(limma_pvals))
betareg_pvals <- betareg_pvals[common_cpgs]
limma_pvals   <- limma_pvals[common_cpgs]
all(names(betareg_pvals) == names(limma_pvals))

## save the hybrid using betareg padj and limma pval 
hybrid_hits <- common_cpgs[betareg_padj < 0.05 & limma_pvals < 0.01]
length(hybrid_hits)
hybrid_hits_df <- as.data.frame(hybrid_hits)
head(hybrid_hits_df)
write.xlsx(hybrid_hits_df, paste0(target_sheet,"_limma_betareg_Hybrid_sig.xlsx"),rowNames=T)

## QC of the results/approaches
png(paste0(target_sheet, "_SV_qqplot.png"), width = 2000, height = 2000, res = 300)
qqplot(-log10(limma_pvals), -log10(betareg_pvals),
       xlab = "-log10(limma p-values)",
       ylab = "-log10(beta regression p-values)",
       main = paste0(sex, " ", behav,": Comparison of Limma vs Beta Regression P-values"))
abline(0,1, col="red")
dev.off()

## Convert to a data frame
df <- data.frame(
  limma = -log10(limma_pvals),
  betareg = -log10(betareg_pvals)
)

## Calculate Spearman's correlation between the two methods
cor_test2 <- cor.test(df$limma, df$betareg, method = "spearman")
rho_val2 <- round(cor_test2$estimate, 3)
p_val2  <- signif(cor_test2$p.value, 3)

cor_lb <- ggplot(df, aes(x = limma, y = betareg)) +
  geom_point(size = 3, alpha = 0.8) +                          # scatter points
  geom_smooth(method = "lm", se = TRUE, color = "green") +      # regression (trend) line
  theme_bw(base_size = 16) +
  labs(
    x = "Limma p-values",
    y = "Betareg p-values",
    title = paste0(sex, " ", behav,": Correlation Between Betareg and Limma Pval")
  ) +
  annotate("text",
           x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
           label = paste0("ρ = ", rho_val2, "\nP = ", p_val2),
           size = 5)
ggsave(paste0(target_sheet, "_betareg_limma_CpGs_Pval.png"), cor_lb, width=8, height=7, dpi=300)

## Statistic testing
betareg_est <- results_betareg_sv1$Estimate
names(betareg_est) <- rownames(results_betareg_sv1)

##==================
limma_logfc <- results_limma$logFC
names(limma_logfc) <- rownames(results_limma)

## Align CpG sites for statistics plot
common_cpgsB <- intersect(names(betareg_est), names(limma_logfc))
betareg_est <- betareg_est[common_cpgsB]
limma_logfc   <- limma_logfc[common_cpgsB]

## Convert to a data frame
dfB <- data.frame(
  limma_lf = limma_logfc,
  betareg_est = betareg_est
)

## Calculate Spearman's correlation between the methods' effect sizes
cor_test_sta <- cor.test(dfB$limma_lf, dfB$betareg_est, method = "spearman")
rho_val_sta <- round(cor_test_sta$estimate, 3)
p_val_sta  <- signif(cor_test_sta$p.value, 3)

##===============
cor_sta <- ggplot(dfB, aes(x = limma_lf, y = betareg_est)) +
  geom_point(size = 3, alpha = 0.8) +                       # scatter points
  geom_smooth(method = "lm", se = TRUE, color = "blue") +   # regression (trend) line
  theme_bw(base_size = 16) +
  labs(
    x = "Limma logFC",
    y = "Betareg Statistics",
    title = paste0(sex, " ", behav,": Correlation Between Limma and Betareg Stat")
  ) +
  annotate("text",
           x = Inf, y = -Inf, hjust = 1.2, vjust = -0.5,
           label = paste0("ρ = ", rho_val_sta, "\nP = ", p_val_sta),
           size = 5)
cor_sta
ggsave(paste0(target_sheet, "_betareg_limma_CpGs_stat.png"), cor_sta, width=8, height=7, dpi=300)

#======================================================================#
##**PART 3: Other EDA ***********************************************###
#======================================================================#
## Separate df for sv
sv_df <- svobj$sv
colnames(sv_df) <- paste0("SV", 1:svobj$n.sv)
sv_df <- as.data.frame(sv_df)
sv_df[] <- lapply(sv_df, as.numeric) 
sv_df

##==================
data_mat <- bv_filtered_df
head(targets)

## Add SVs to phenotype data
sample_info2 <- targets[, c("sample", "Group", "batch", behav)]
pheno_df <- cbind(sample_info2, sv_df)
rownames(pheno_df) <- pheno_df$sample
pheno_df$sample <- NULL
pheno_df <- pheno_df[colnames(data_mat), ]

## method 1: PCA EDA
##====================
data_mat_clean <- data_mat[ apply(data_mat, 1, function(x) all(is.finite(x))), ]
data_mat_clean <- data_mat_clean[ apply(data_mat_clean, 1, sd) > 0, ]

##===================
pca_res <- prcomp(t(data_mat_clean), scale. = F)
pca_before <- prcomp(t(data_mat_clean), scale. = F)

## Extract PCA results
#pca_data <- as.data.frame(pca_res$x)
pca_data <- as.data.frame(pca_res$x) %>%
  rownames_to_column("sample") %>%
  left_join(pheno_df %>% rownames_to_column("sample"), by = "sample")

## Set explicit factor levels
pca_data$Group <- factor(pca_data$Group, 
                         levels = c("BBzP", "BPF", "CtrlA1", "CtrlA2", "CtrlA4", "DINCH", "TPHP"))

## Define distinct shapes for each group
group_shapes <- c(
  "BBzP"   = 16,  # filled circle
  "BPF"    = 17,  # triangle
  "CtrlA1" = 15,  # square
  "CtrlA2" = 18,  # diamond
  "CtrlA4" = 3,   # plus
  "DINCH"  = 4,   # cross
  "TPHP"   = 8   # star
)

## Calculate explained variance
var_explained <- round(100 * summary(pca_res)$importance[2, 1:2], 1)

## PCA plot
p_pca <- ggplot(pca_data, aes(x = PC1, y = PC2, color = Group, shape = Group)) +
  geom_point(size = 5, alpha = 0.9) +   # increased point size
  scale_shape_manual(values = group_shapes) +
  theme_minimal(base_size = 16) +
  labs(
    title = paste0("B-value: Pre-batch-correction PCA in ", sex," ", behav),
    x = paste0("PC1 (", var_explained[1], "%)"),
    y = paste0("PC2 (", var_explained[2], "%)")
  ) +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )
p_pca

##==================
p_pcaE <- ggplot(pca_data, aes(x = PC1, y = PC3, color = Group, shape = Group)) +
  geom_point(size = 5, alpha = 0.9) +        # points
  stat_ellipse(aes(fill = Group), geom = "polygon", alpha = 0.2, color = NA) +
  scale_shape_manual(values = group_shapes) +
  theme_minimal(base_size = 16) +
  labs(
    title = paste0("B-value: Pre-batch-correction PCA in ", sex," ", behav),
    x = paste0("PC1 (", var_explained[1], "%)"),
    y = paste0("PC2 (", var_explained[2], "%)")
  ) +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )
p_pcaE

##====================
## Save plots (high-resolution)
ggsave(paste0(target_sheet,"_bvalue_PCA_meth_b4BC.png"), p_pca, width = 8, height = 7, dpi = 300)
ggsave(paste0(target_sheet,"_bvalue_PCA_methy_b4BCE.png"), p_pcaE, width = 8, height = 7, dpi = 300)

##After BC ###############################################
##Batch correction using limma::removeBatchEffect
sv_colsB <- grep("^SV", names(pheno_df), value = TRUE)
corrected_mat <- limma::removeBatchEffect(
  bv_filtered_df,
  batch = pheno_df$batch,
  group = pheno_df$Group,
  covariates = as.matrix(pheno_df[, sv_colsB, drop = FALSE])
)
corrected_mat_clean <- corrected_mat[ apply(corrected_mat, 1, function(x) all(is.finite(x))), ]
corrected_mat_clean <- corrected_mat_clean[ apply(corrected_mat_clean, 1, sd) > 0, ]

## PCA plot
pca_res <- prcomp(t(corrected_mat_clean), scale. = F)
pca_after <- prcomp(t(corrected_mat_clean), scale. = F)

pca_data <- as.data.frame(pca_res$x) %>%
  rownames_to_column("sample") %>%
  left_join(pheno_df %>% rownames_to_column("sample"), by = "sample")

#Set explicit factor levels
pca_data$Group <- factor(pca_data$Group, 
                         levels = c("BBzP", "BPF", "CtrlA1", "CtrlA2", "CtrlA4", "DINCH", "TPHP"))

# Define distinct shapes for each group
group_shapes <- c(
  "BBzP"   = 16,  # filled circle
  "BPF"    = 17,  # triangle
  "CtrlA1" = 15,  # square
  "CtrlA2" = 18,  # diamond
  "CtrlA4" = 3,   # plus
  "DINCH"  = 4,   # cross
  "TPHP"   = 8   # star
  )

p_pcaB <- ggplot(pca_data, aes(x = PC1, y = PC2, color = Group, shape = Group)) +
  geom_point(size = 5, alpha = 0.9) +
  scale_shape_manual(values = group_shapes) +
  theme_minimal(base_size = 16) +
  labs(
    title = paste0("B-value: SVA-corrected PCA in ", sex, " ", behav),
    x = paste0("PC1 (", var_explained[1], "%)"),
    y = paste0("PC2 (", var_explained[2], "%)")
  ) +
  theme(legend.position = "bottom")
p_pcaB

##=================
p_pcaBE <- ggplot(pca_data, aes(x = PC1, y = PC2, color = Group, shape = Group)) +
  geom_point(size = 5, alpha = 0.9) +        # points
  stat_ellipse(aes(fill = Group), geom = "polygon", alpha = 0.2, color = NA) +
  scale_shape_manual(values = group_shapes) +
  theme_minimal(base_size = 16) +
  labs(
    title = paste0("B-value: SVA-corrected PCA in ", sex, " ", behav),
    x = paste0("PC1 (", var_explained[1], "%)"),
    y = paste0("PC2 (", var_explained[2], "%)")
  ) +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )
p_pcaBE

##====================
ggsave(paste0(target_sheet,"_bvalue_PCA_meth_AFBC.png"), p_pcaB, width = 8, height = 7, dpi = 300)
ggsave(paste0(target_sheet,"_bvalue_PCA_meth_AFBCE.png"), p_pcaBE, width = 8, height = 7, dpi = 300)

################################################################################
##==== Use M-Value ====#
## Ensure sample order matches phenotype
data_mat <- M_filtered_df
head(pheno_df)

## PCA analysis
data_mat_clean <- data_mat[ apply(data_mat, 1, function(x) all(is.finite(x))), ]
data_mat_clean <- data_mat_clean[ apply(data_mat_clean, 1, sd) > 0, ]
pca_res <- prcomp(t(data_mat_clean), scale. = F)
pca_before <- prcomp(t(data_mat_clean), scale. = F)

## Extract PCA results
pca_data <- as.data.frame(pca_res$x) %>%
  rownames_to_column("sample") %>%
  left_join(pheno_df %>% rownames_to_column("sample"), by = "sample")

## Set explicit factor levels
pca_data$Group <- factor(pca_data$Group, 
                         levels = c("BBzP", "BPF", "CtrlA1", "CtrlA2", "CtrlA4", "DINCH", "TPHP"))
## Define distinct shapes for each group
group_shapes <- c(
  "BBzP"   = 16,  # filled circle
  "BPF"    = 17,  # triangle
  "CtrlA1" = 15,  # square
  "CtrlA2" = 18,  # diamond
  "CtrlA4" = 3,   # plus
  "DINCH"  = 4,   # cross
  "TPHP"   = 8   # star
  )

## Calculate explained variance
var_explained <- round(100 * summary(pca_res)$importance[2, 1:2], 1)

## PCA Plot
p_pcaMA <- ggplot(pca_data, aes(x = PC1, y = PC2, color = Group, shape = Group)) +
  geom_point(size = 5, alpha = 0.9) +   
  scale_shape_manual(values = group_shapes) +
  theme_minimal(base_size = 16) +
  labs(
    title = paste0("M-value: Pre-batch-correction PCA in ", sex," ", behav),
    x = paste0("PC1 (", var_explained[1], "%)"),
    y = paste0("PC2 (", var_explained[2], "%)")
  ) +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )
p_pcaMA
ggsave(paste0(target_sheet,"_malues_PCA_meth_b4BC.png"), p_pcaMA, width = 8, height = 7, dpi = 300)

##===== After BC ==========#
corrected_mat <- removeBatchEffect(M_filtered_df, batch = pheno_df$batch, 
                                   group = pheno_df$Group,
                                   covariates = as.matrix(pheno_df[, sv_colsB, drop = FALSE])
)
corrected_mat_clean <- corrected_mat[ apply(corrected_mat, 1, function(x) all(is.finite(x))), ]
corrected_mat_clean <- corrected_mat_clean[ apply(corrected_mat_clean, 1, sd) > 0, ]

# PCA plot
pca_res <- prcomp(t(corrected_mat_clean), scale. = F)
pca_after <- prcomp(t(corrected_mat_clean), scale. = F)
##====================
pca_data <- as.data.frame(pca_res$x) %>%
  rownames_to_column("sample") %>%
  left_join(pheno_df %>% rownames_to_column("sample"), by = "sample")

## Set explicit factor levels
pca_data$Group <- factor(pca_data$Group, 
                         levels = c("BBzP", "BPF", "CtrlA1", "CtrlA2", "CtrlA4", "DINCH", "TPHP"))

## Define distinct shapes for each group
group_shapes <- c(
  "BBzP"   = 16,  # filled circle
  "BPF"    = 17,  # triangle
  "CtrlA1" = 15,  # square
  "CtrlA2" = 18,  # diamond
  "CtrlA4" = 3,   # plus
  "DINCH"  = 4,   # cross
  "TPHP"   = 8   # star
  )

##================
var_explained <- round(100 * summary(pca_res)$importance[2, 1:2], 1)
p_pcaMB <- ggplot(pca_data, aes(x = PC1, y = PC2, color = Group, shape = Group)) +
  geom_point(size = 5, alpha = 0.9) +
  scale_shape_manual(values = group_shapes) +
  theme_minimal(base_size = 16) +
  labs(
    title = paste0("M-value: SVA-corrected PCA in ", sex, " ", behav),
    x = paste0("PC1 (", var_explained[1], "%)"),
    y = paste0("PC2 (", var_explained[2], "%)")
  ) +
  theme(legend.position = "bottom")
p_pcaMB
ggsave(paste0(target_sheet,"_mvalue_PCA_meth_AFBC_lociB.png"), p_pcaMB, width = 8, height = 7, dpi = 300)

## correlation summary window levels
cor.test(pca_before$x[,1], as.numeric(as.factor(pheno_df$batch)))
cor.test(pca_after$x[,1], as.numeric(as.factor(pheno_df$batch)))
